### ISSUE TITLE
Use FeatureSummary instead of find_package(FOO REQUIRED)

### ISSUE THREAD

**Issue by lbeltrame** [Martchus/syncthingtray#11]
`FeatureSummary` allows CMake to finish configuring and yet print out properly the dependencies that are missing, divided in optional and required.

```cmake
include(FeatureSummary)
find_package(FOO) # Note no REQUIRED
set_package_properties(FOO TYPE REQUIRED URL http://example.com PURPOSE "Required to foo the bar.")

# at the end
feature_summary(WHAT ALL FATAL_ON_MISSING_REQUIRED_PACKAGES)
```

This is makes it easier to:

a. Track dependencies
b. Ensure all dependencies are installed at once.

Note: I'm not sure which is the minimum CMake version you support.

**Comment by Martchus** [comment]
Thanks for the feedback. I'll add this feature when I have time. Or would you like to create a PR yourself?

> Note: I'm not sure which is the minimum CMake version you support.

Me neither. I'm always using the latest version myself and I'm not very concerned about backward compatibility.

---

Note that all dependencies should be mentioned in the README.md. So this information should actually be available. Did I miss something there?

There are also packages for Arch LInux and Tumbleweed mentioned in the README.md. The list of dependencies is included in these package definitions as well. And those should definitely be complete, otherwise the packages would not build.

Considering that the information is already available, I'd say this is not very high on the prio list.

**Comment by lbeltrame** [comment]
It helps packagers in tracking dependencies mostly. Given the low-effort of the task, I'll look into it.

**Comment by Martchus** [comment]
I don't think this is low-effort.

At least it requires editing lots of files in different repositories. Eg. `include(FeatureSummary)` should maybe go into `BasicConfig.cmake` (in `c++utilities`). The `find_package` for Qt modules would go to Qt linkage in `qtutilities`. A lot of other occurrences of `find_package` must be changed as well.

Since the changed behavior breaks backward compatibility of c++utilities/qtutilities CMake modules, it must be made optional and only be enabled if some other variable is set, eg. `META_USE_FEATURE_SUMMARY`.

**Comment by lbeltrame** [comment]
> I don't think this is low-effort.

I obviously said this *before* looking at the whole picture. Famous last words. ;)

> include(FeatureSummary) should maybe go into BasicConfig.cmake (in c++utilities). 

No, the whole point of FeatureSummary is that it should be there for every project. If I use syncthingtray I should get informed that I lack c++utilities, for example.
FTR, Is there any reason why the `find_package` calls are spread across different directories and even require different versions?

**Comment by Martchus** [comment]
> No, the whole point of FeatureSummary is that it should be there for every project.

Indeed, then it would not work for c++utilities. Then the additional line must be included in each an every project.

> Is there any reason why the find_package calls are spread across different directories

I think of the different subdirectories as own subprojects which might be moved out to a different repository. Eg. the Dolphin plugin and the Plasmoid could be moved to a separate repository for KDE integration if it grows too big. The top-level project file is just to build everything conveniently in one step.

>  and even require different versions?

If eg. only the optional "leaf project" `plasmoid` requires the latest `c++utilities`, why should other parts such as the CLI also require that version?

---

BTW: For which platform are you trying to build/package this? I'm just asking because you obviously didn't just try to convert the Arch/Tumbleweed/mingw-w64 packages for you platform (that would have been my approach). If you created a package, you could link it in the README.md.

**Comment by lbeltrame** [comment]
It would be nice to get this in officially for Tumbleweed (I'm part of the KDE team), but as it is packaging this if packager != developer, it is not really sustainable in the long run.
I'm trying to apply some (good IMO, but that's just the opinion of a passing-by person) habits from my downstream (oS) and upstream (KDE) FOSS involvement.

**Comment by Martchus** [comment]
> It would be nice to get this in officially for Tumbleweed

I could try to submit the packages I have already created.

> but as it is packaging this if packager != developer, it is not really sustainable in the long run.

Not sure what you mean by that. (I don't understand the sentence grammatically.)
