### ISSUE TITLE
Orphan plasmoid appears on system tray - KDE

### ISSUE THREAD

**Issue by maguilara** [Martchus/syncthingtray#110]
**Relevant components**
* [ ] Standalone tray application (based on Qt Widgets)
* [x] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: 1.1.10-1, 6.5.0-1, 5.11.1-1
* Qt version: qt5-base 5.15.2+kde+r222-2 (qt qt5)
* C++ compiler (name and version):  gcc 11.1.0-1 (base-devel)
* C++ standard library (name and version): gcc-libs 11.1.0-1 
* Operating system (name and version): Arch Linux 

**Bug description**
An orphan plasmoid appears on the system tray after installing STT andlogging out from the current session. Cannot be deactivated/closed by any means. It will stay even after starting the STT process., coexisting 2 or more tray icons if more STT process are instanced. Will only disappear after uninstalling STT and logging out from the current session. 
**Steps to reproduce**
1. Install STT
2. Log out from current session.
3. Log in, STT tray will appear even when STT hasn't been invoked.

**Expected behavior**
Tray icon should only appear when process is running

**Screenshots**
Showin both plasmoids, the one working with the stt process can be closed
![image](https://user-images.githubusercontent.com/29683592/132998170-1e03fe92-cdbd-4e84-8869-5af4fdf3221b.png)
The other one can't be closed
![image](https://user-images.githubusercontent.com/29683592/132998198-ab600902-e030-4368-b7d3-66f32c6baeb0.png)
Even when no STT process are running, the orphan plasmoid stays there
![image](https://user-images.githubusercontent.com/29683592/132998417-24373b99-4430-4757-af44-52e117a1d61d.png)

**Additional context**

**Comment by Martchus** [comment]
Does this help? https://github.com/Martchus/syncthingtray/issues/96#issuecomment-865355073

Btw, I'm not sure why the icon is shown by default and why the setting is sometimes even reverted. Maybe some Plasma devs would know.

**Comment by maguilara** [comment]
> Does this help? [#96 (comment)](https://github.com/Martchus/syncthingtray/issues/96#issuecomment-865355073)
If I choose "Always hidden", the icon does disappear, but I want to use it "Show when relevant" (e.g. to know that ST has been started successfully).  I think that for some reason is hardcoded into the system tray even when no STT is running,

**Comment by Martchus** [comment]
The states when the Plasmoid is considered "relevant" are not hard-coded. You can select them in the Plasmoid's settings.

**Comment by maguilara** [comment]
I did something that made the orphan plasmoid disappear. The plasmoid's settings you mention are not present in the "functional" tray, yet they are in the "orphan" tray. I toggled all the states just to test them and it's now gone from my system tray. Is this how is meant to work? Not sure if this is the solution or just a workaround.

**Comment by Martchus** [comment]
First I'd like to note that the Plasmoid being displayed within the System Tray Plasmoid is a Plasma feature and does not mean this Plasmoid is orphaned (whatever this exactly means in this context). If you don't want the Plasmoid being displayed in that way you can disable it like described in the previously liked comment. If you only want to display it in certain states you can also configure it that way. It is intended that the Plasmoid-specific configuration is *not* accessible from the stand-alone tray application because it is stored in Plasma's config per Plasmoid instance.

By the way, under Arch Linux + Plasma desktop I recommend to actually use the Plasmoid instead of the stand alone application. That also means starting Syncthing as systemd user unit and enabling the systemd integration of the Plasmoid (instead of using the launcher which is more intended for non-systemd systems like Windows). I'd still disable the Plasmoid within the System Tray Plasmoid and rather add it separately to be able to increase its size.

**Comment by Martchus** [comment]
No response so I cannot help any further.
