### ISSUE TITLE
Use icons from KDE theme

### ISSUE THREAD

**Issue by mrpink17** [Martchus/syncthingtray#121]
**Relevant components**
* [ ] Standalone tray application (based on Qt Widgets)
* [X] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Is your feature request specific to a certain platform/environment? Please specify.**
KDE Plasma

**Is your feature request related to a problem? Please describe.**
The app uses custom icons that don't look "standard" in KDE Plasma, they are also a bit blurry

**Describe the solution you'd like**
Use icons from KDE theme

**Additional context**
![Screenshot_20211215_231815](https://user-images.githubusercontent.com/13852200/146273719-49a4fbd9-01c3-4ea8-a70a-c35603938fa5.png)

**Comment by Martchus** [comment]
I'm using ForkAwesome icons in consistency with Syncthing's official GUI. Especially for the icons within the expandable list items that makes also most sense in my opinion. For consistency with that I also like to use ForkAwesome for the icons close to that list view. That has also the advantage (over the system icon theme) that I can rely on the icons being actually present. The ForkAwesome icons are quite neutral themselves so they should fit in most icon themes.

Maybe it could be made configurable, e.g. adding an option to use the system's icon theme as much as possible.

**Comment by mrpink17** [comment]
Yes, it would be great!

**Comment by sten0** [comment]
Because Syncthing is a "killer app", I think that in the future the KDE project may be amenable to a PR that adds the required SVG icons to the base set.  This would take care of question of icon availability.  If a new enough version of Plasma is not detected at compile time, then qtforkawesome would be the only available option.  It also seems like Qtforkawesome must be retained for use of the tray icon on non KDE Plasma systems.

I worry that mixing the two might cause scaling issues on HiDPI displays that use a non-default scaling factor.  More large-scale use will reveal if users want sharper icons, and HiDPI users can be quite passionate about this sort of thing.

No comment on aesthetics, and I believe there's an argument to be made about how using the same icons as the Syncthing web interface makes the following semantic statement: it makes the user aware they're interacting with a web thing rather than a desktop thing.  That can be a good or a bad thing, depending on one's perspective.

**Comment by Martchus** [comment]
Note that currently my approach is to use icons from the normal icon theme everywhere (dialogs, context menus, …) except for the main tray icon where I use ForkAwesome icons. Especially for the view it just makes more sense to be consistent with Syncthing's normal GUI. Note that ForkAwesome is quite neutral and look good together with most other icon themes (and Plasma themes) and the icons will follow the system's color palette. HiDPI should not be a concern because the font icons also scale well.

However, I'm also open for implementing a config switch to use system icons as aggressively as possible. I just haven't implemented it myself because I personally don't see it as better.

**Comment by sten0** [comment]
>
> Note that currently my approach is to use icons from the normal icon theme
> everywhere (dialogs, context menus, …) except for the main tray icon where
> I use ForkAwesome icons. Especially for the view it just makes more sense
> to be consistent with Syncthing's normal GUI. Note that ForkAwesome is
> quite neutral and look good together with most other icon themes (and
> Plasma themes) and the icons will follow the system's color palette. HiDPI
> should not be a concern because the font icons also scale well.
>
> However, I'm also open for implementing a config switch to use system
> icons as aggressively as possible. I just haven't implemented it myself
> because I personally don't see it as better.
>

:-)  I agree that it's a question of preference, and choice of
orientation.  At this time I don't have a strong preference either way
(although I'm biased towards svg, and am also a supporter of user
theming).  I agree that HiDPI shouldn't be a problem, but the icons in
@mrpink17's screenshot do look a bit blurry to me, but to be fair, so do
the fonts.  It looks like it might be Ubuntu-style hinting and/or
aliasing.  Does Qt ForkAwesome already override desktop preferences like
these?  If not, that might be a way to resolve the fuzziness.  In theory,
font icons should scale similarly well to svg ones after all!

**Comment by Martchus** [comment]
> Does Qt ForkAwesome already override desktop preferences like these?

It renders the glyphs like any other text would be rendered within the Qt application. Normally Qt is using freetype2 to render fonts (at least under GNU/Linux) so settings affecting freetype2 should have effect. The settings done via `systemsettings5` definitely have effect (although you need to restart the application, in case of the Plasmoid that's `plasmashell` itself).

And yes, the screenshot looks blurry (including the normal text rendering).

**Comment by sten0** [comment]
ping

**Comment by Martchus** [comment]
Adding the enhancement label so stale bot won't close it.

---

Note that the main problem is that the free desktop specification doesn't provide all icons we need so we'd still end up with a mix of KDE and ForkAwesome icons. Therefore I don't think that this is very worthwhile. At least one needs to ensure that the mixup won't be too bad (e.g. still use ForkAwesome consistently in the expandable details). Of course it is actually already a mixup but at least with a clear distinction where which icons are used (see https://github.com/Martchus/syncthingtray/issues/121#issuecomment-1088473032).

**Comment by Martchus** [comment]
Implemented for the Qt Widgets version and the Plasmoid as optional feature. On the Plasmoid it looks rather ugly when the current freedesktop icon theme (e.g. Breeze light) doesn't match the Plasma theme (e.g. some dark theme). I suppose I actually needed to use the icons from the Plasma theme here (and not from the freedesktop icon theme).

**Comment by Martchus** [comment]
> I suppose I actually needed to use the icons from the Plasma theme here (and not from the freedesktop icon theme).

It looks like this aspect is not going to be relevant in Plasma 6 anymore (see https://pointieststick.com/2023/07/26/what-we-plan-to-remove-in-plasma-6). Since it was the only improvement left to do I'm closing this issue.
