### ISSUE TITLE
Failure to connect on start when using the "Launch Syncthing" option

### ISSUE THREAD

**Issue by shapirus** [Martchus/syncthingtray#15]
When the "Launch Syncthing when starting the tray icon" option is enabled and syncthingtray is started, the daemon is launched successfully, but the tray application reports an error (in my case shown via the standard KDE desktop notification mechanism):

![screenshot_20180402_095034](https://user-images.githubusercontent.com/725402/38186533-2a1c06a0-365c-11e8-8360-a824c22ba02d.png)

Most likely this happens because syncthingtray tries to connect too soon after launching the syncthing daemon, before it even has a chance to start listening. Further attempts to show the UI or the Web UI do succeed.

It can be solved by trying to connect in a loop several times, with a reasonable (say 0.5 second) delay between retries, failing after a certain (configurable?) number of attempts, and generating an error notification only if no attempt succeed.

Additionally, I always observe a `[syncthingtray] <defunct>` zombie process when syncthingtray is running normally. I'm not sure whether that's a related issue or not.

**Comment by Martchus** [comment]
I have to admit that I don't test the launcher very extensive. Yes, maybe I should give it some startup time before failing.

Under Linux I would recommend to start Syncthing via `systemctl --user start syncthing`. The tray has systemd integration as well and can consider the unit status to prevent such issues. This requires a running session DBus started via systemd.

Not sure about the zombie. How do you launch syncthing tray and where does this log message appear?

Since you're using KDE, I'd also like to note that there's a plasmoid as well.

**Comment by shapirus** [comment]
> Under Linux I would recommend to start Syncthing via systemctl --user start syncthing
Yes that's a possible option too. However, it won't work for those who want their syncthing stack running only as long as the tray application is running. In my case it makes no difference, but I can imagine how someone would like it the launcher way.

> Not sure about the zombie. How do you launch syncthing tray and where does this log message appear?
It doesn't really matter how I launch it: be it from command line or the desktop autostart settings, it's all the same. The zombie process can be seen in the process list. Zombie process appear when you fork() children and do not wait() on them when they finish.
This may be related to the Appimage method of running it, by the way (it might do forks without waits, I'm not sure). I haven't tested other methods, since there is no Debian package, checkinstall fails to build a .deb, and I don't really want to install it using 'make install' in order to avoid filesystem pollution. Hence also no plasmoid option for me at present.

p.s. syncthingtray is the best native app to render syncthing's UI that I've found so far. Some of them are primitive web-ui wrappers, some (namely syncthing-gtk) fail to provide a system tray entry on some of my KDE setups and have a brain damaged interface. Yours is just right. Please don't abandon it, it looks like a good piece of software :).

**Comment by Martchus** [comment]
I refactored suppressing notifications for the local instance. The same logic as for the systemd service should now be applied to the internal launcher. This gives Syncthing a few seconds to start. If your system uses systemd, also a standby-wakeup is detected and Syncthing is given a few seconds before showing any error messages.

What's still missing is the start/stop button being available also for the internal launcher.

> Zombie processes appear when you fork() children and do not wait() on them when they finish.

I know. That's why the tray terminates the child processes before it terminates itself. However, there's a 3 seconds timeout and then *I belief* Qt kills the process. I now increased the timeout to infinity. Additionally, after 3 seconds, the user is now asked to kill the process (which is then killed for sure) or to keep waiting. This should prevent the possibility of becoming a zombie.

> This may be related to the Appimage method of running it, by the way (it might do forks without waits, I'm not sure).

That could also make a difference. I only created the AppImage for the users, I don't like to use it myself. Hence it is not tested very well, too.

> checkinstall fails to build a .deb

I don't know what checkinstall is, but if you like to create a Debian package, just have a look at the existing Arch Linux, openSUSE and Fedora packages or the build scripts used for the AppImage. It shouldn't be hard to convert them into Debian format if one is familiar with Debian packaging (I'm not).

> I don't really want to install it using 'make install' in order to avoid filesystem pollution

It is possible to specify a custom install prefix (eg. somewhere in your home directory). It works like for any other CMake project. See the Arch Linux packages for an example.

> Please don't abandon it, it looks like a good piece of software :).

Thanks, and I have no plans to abandon it :-)

**Comment by Martchus** [comment]
I re-triggered the AppImage build on OBS in case you would like to test the latest changes: https://build.opensuse.org/package/binaries/home:mkittler:appimage:vcs/syncthingtray/AppImage

**Comment by Martchus** [comment]
I assume it directly crashes on startup and doesn't even show up. Under Arch Linux and Tumbleweed I can run the latest state (master branch) without running into this issue. So I *guess* this error is because of some AppImage-related changes. Can you provide a coredump with stacktrace?

Here, on my Arch Linux system I also can't use the AppImage because of a [known issue](https://github.com/probonopd/linuxdeployqt/issues/261). Getting a coredump is quite easy:

```
[martchus@martchus-arch downloads]$ chmod +x syncthingtray-1522866132.a805de8-Build2.2.glibc2.14-x86_64.AppImage                                                                                                                                                                                                      
[martchus@martchus-arch downloads]$ ./syncthingtray-1522866132.a805de8-Build2.2.glibc2.14-x86_64.AppImage                                                                                                                                     
Speicherzugriffsfehler (Speicherabzug geschrieben)
[martchus@martchus-arch downloads]$ wget 'https://download.opensuse.org/repositories/home:/mkittler:/appimage:/vcs/AppImage/syncthingtray-1522866132.a805de8-Build2.2.glibc2.14-x86_64.AppImage'
[martchus@martchus-arch downloads]$ coredumpctl info -1
           PID: 7787 (syncthingtray)
           UID: 1000 (martchus)
           GID: 1004 (martchus)
        Signal: 11 (SEGV)
     Timestamp: Sat 2018-04-07 17:14:50 CEST (1min 19s ago)
  Command Line: syncthingtray
    Executable: /tmp/.mount_syncth7q1e4G/usr/bin/syncthingtray
 Control Group: /user.slice/user-1000.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1000.slice
       Session: c1
     Owner UID: 1000 (martchus)
       Boot ID: b57e2bcad0c0465898b65a8548abf66c
    Machine ID: 31e2bf5faa674059988077d8723543f1
      Hostname: martchus-arch
       Storage: none
       Message: Process 7787 (syncthingtray) of user 1000 dumped core.
                
                Stack trace of thread 7787:
                #0  0x00007fbbcbb13077 __ehdr_start (ld-linux-x86-64.so.2)
```
If you're using systemd as well, you can directly follow this steps. Maybe the stack trace is more interesting in your case.

To exclude app image issues, you could also try to build it yourself. There are steps to "build this straight" in the readme. Like I already said:

> It is possible to specify a custom install prefix (eg. somewhere in your home directory). It works like for any other CMake project. See the Arch Linux packages for an example.

And besides, you don't even need to install. Just click on the executable in the build directory. The build system automatically sets rpath, so it should find its libraries without extra effort.

**Comment by shapirus** [comment]
Here's an update.
I have downloaded the latest AppImage binary (from Apr 22nd) which starts fine and doesn't crash.
This time there are no "connection refused" messages, but syncthingtray's tray icon is grey on start, and when I click on it, the window contents look as if it is not connected to the daemon. When I click the "connect" button or select the "primary instance" in the instance selection widget, then it apparently connects to the core and everything works as expected.

**Comment by Martchus** [comment]
I have done some relevant changes since the last build so I makes sense to test again with the lasted build. For that purpose, I re-triggered the AppImage build on OBS: https://build.opensuse.org/package/show/home:mkittler:appimage:vcs/syncthingtray

That the error notification is suppressed is actually a (new) feature. The tray can ignore in-availability after startup or suspension and hence suppress the notification. This number of seconds after startup when in-availability should be ignored is configurable in notification settings.

Did you enable 'Consider process status for reconnect attempts' in launcher settings? If not, the tray should *not* automatically connect when the process is started.

Note that 'Consider process status for reconnect attempts' can not be enabled by default, because there are other ways of starting Syncthing. Then it makes no sense to take the status of the internal launcher into account. Instead, the status of the systemd unit is relevant (for instance).

Note that if you configure auto-reconnect for that connection, the tray should connect in this interval. (Except you enabled 'Consider process status for reconnect attempts' and the process is not running.)

---

I haven't concluded my own testing since the last refactoring and changes. So the current build might not work 100% as expected.

> I have downloaded the latest AppImage binary (from Apr 22nd)

To know for sure which version you're using, it would be better to give me the concrete version (Git commit ID which is part of the AppImage's file name). The obvious reason is that it is possible to build multiple versions on the same day :-)

As explained, the behavior depends a lot on your settings. So it would make sense to send me your configuration file (located under `~/.config/syncthingtray.ini`). Be sure to remove sensible data like your API key.
