### ISSUE TITLE
Plasmoid not displayed?

### ISSUE THREAD

**Issue by alxlg** [Martchus/syncthingtray#17]
I installed everything from sources, systray icon works as expected but I can't use the plasmoid: it appears in "add new widgets" panel on the left, but when I drag it to desktop or panel it doesn't appear. I'm on KDE Neon (Ubuntu 16.04).

**Comment by Martchus** [comment]
Strange that it doesn't appear at all. So I assume you don't even get an error message?

I never had this problem at any time during development. At least some error was shown (or the entire shell crashed).

Do you get any useful console output from plasmashell? What happens if you [open it in plasmodviewer](https://github.com/Martchus/syncthingtray/blob/master/plasmoid/testing.md) or plasmawindowed?

And how did you install it? Since I don't provide packages for any Debian-based distros, I assume you did a custom build? How did you install the plasmoid then?

**Comment by Martchus** [comment]
I know see the same problem under Tumbleweed. That is very strange because I didn't change my packaging for Tumbleweed and it just ceased to work after some update - unlike the Arch Linux build which is still loaded fine.

Unfortunately the log of `plasmashell`/`plasmoidviewer`/`plasmawindowed` is not helpful. It only says the plasmoid can not be loaded.

Interestingly, my [development setup](https://github.com/Martchus/syncthingtray/blob/master/plasmoid/testing.md) still works. So that would be a workaround (beside using the regular tray icon).

Not sure what I can do about it, though. At least right now I'm running out of ideas.

**Comment by alxlg** [comment]
@Martchus may I suggest to get in contact with Plasma developers? I know them because I contributed to visual design stuff and I believe they would be happy to help you.

**Comment by Martchus** [comment]
I've already chatted a little bit with one developer on IRC but we didn't come to a conclusion. I believe the error reporting should be better. `Unable to load applet ...` is just not enough.

**Comment by Martchus** [comment]
We now found out that in my case the version of plasma-framework the plasmoid was built against (by OBS) was newer than the version installed on my system. So just a wrong configuration on my side.

In your case the plugin (the file `libsyncthingplasmoid.so`) is likely just installed in the wrong place. You can specify the right place by adding `-DQT_PLUGIN_DIR=/the/right/place` to the CMake arguments.

You can query the right place to install the plugin to from qmake: `qmake-qt5 -query QT_INSTALL_PLUGINS`

**Comment by Martchus** [comment]
I've recently added my findings to the README: https://github.com/Martchus/syncthingtray#troubleshooting-kde-integration

Maybe this covers your problem. I've also updated `qtutilities` to do the `qmake-qt5 -query QT_INSTALL_PLUGINS` automatically on the CMake run.

**Comment by alxlg** [comment]
@Martchus Hey I just took the time to rebuild everything and it works fine now. I'm still on KDE Neon but now it's based on Ubuntu 18.04. On my side you can close the issue, thank for your help and thank you very much for the plasmoid, I love it!

**Comment by Martchus** [comment]
I'm glad to help. Good that the issue is fixed. Since I've updated `c++utilities` and also the documentation I guess the issue can be closed.
