### ISSUE TITLE
Always getting the correct AUTOSTART_EXEC_PATH ?

### ISSUE THREAD

**Issue by doronbehar** [Martchus/syncthingtray#176]
---

**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

---
Hello @Martchus,

Thanks to a [peer review at Nixpkgs](https://github.com/NixOS/nixpkgs/pull/209062#pullrequestreview-1236514452), I came to realize that this cmake variable design perhaps wasn't right. I think it'd be much more neat (if you'd accept the idea) to drop this cmake variable, and do the following near that `desktopFile.write` line at `settingsdialog.cpp`:

- Detect the directory of the current executable (Perhaps use [`boost::dll::program_location`](https://www.boost.org/doc/libs/1_65_1/doc/html/boost/dll/program_location.html)).
- Locate for the `Exec=` line the wrapped `syncthingtray` path, according to the return value of `program_location`.

I'd appreciate any advice before I try to implement this :)

Thanks.

**Comment by Martchus** [comment]
1. The current use of [`QCoreApplication::applicationFilePath()`](https://doc.qt.io/qt-6/qcoreapplication.html#applicationFilePath) should be equivalent to [`boost::dll::program_location`](https://www.boost.org/doc/libs/1_65_1/doc/html/boost/dll/program_location.html). I would prefer keep using the former to avoid pulling in another dependency. (And yes, I'm already using Boost because Boost.Process is clearly better than `QProcess` but in general I'd still like to stick to Qt when possible.)
2. I don't think I understand the second point. What is meant by "wrapped"? So far we simply assign the program location to `Exec=` which makes most sense in my opinion¹. So what in addition is needed for your Nixpkgs setup?
3. The `.desktop` file should generally still contain the full executable path because the `syncthingtray` executable might not be in `PATH`, e.g. when one does a custom installation. (If you wanted a relative path there, you could use `AUTOSTART_EXEC_PATH` to do that.)

---

¹ The only exceptions are the AppImage case (which should be kept as-is) and the `AUTOSTART_EXEC_PATH` override (which I personally don't care much about but we might now want to keep as well for the sake of compatibility).

**Comment by doronbehar** [comment]
2. Maybe I should have wrote "locate the wrapping `syncthingtray`". Basically, Nix' build process takes `$out/bin/syncthingtray` that cmake builds, renames it to `$out/bin/.syncthingtray-wrapped` and creates a bash script in `$out/bin/syncthingtray` that calls `$out/bin/.syncthingtray-wrapped` with environmental variables needed mostly on NixOS. The script `$out/bin/syncthingtray` is the wrapper, and `$out/bin/.syncthingtray-wrapped` is the wrapped executable. If you'd try to run on a NixOS machine the `.syncthingtray-wrapped` executable without the wrapper, you'd get nasty errors.

Anyway, I was thinking about the following change, that would allow Nix to not set the newly introduced `AUTOSTART_EXEC_PATH`: https://github.com/Martchus/syncthingtray/pull/177
