### ISSUE TITLE
Provide some changelog for version releases would be appreciated

### ISSUE THREAD

**Issue by wohenbushuang** [Martchus/syncthingtray#185]
The change log in the forum link in README remains unchanged since last year

**Comment by Martchus** [comment]
I don't see me writing changelogs for every damn release. I suppose I could just add a summary based on the Git log like Syncthing itself. However, you can actually just browser the commit history yourself right now so that would likely not add much value.

I'm usually updating the forum when something cool/bigger happens. However, that hasn't happened for a while. Maybe I'll nevertheless give some summary as the detail improvements have definitely piled up over the last few releases.

**Comment by Martchus** [comment]
I've just replied in the forum. Note that the last post hasn't actually been *that* long ago. It was actually from the last quater of last year.

**Comment by wohenbushuang** [comment]
Thanks for your reply. This idea comes from that, as an user, although I had subscribed the release notification, I don't care about some minor changes and there is no need to upgrade everytime. The releases notes will help me to decide whether it is worth to download and replace the old one.

Thanks again for your effort on this useful GUI application.

**Comment by Martchus** [comment]
> The releases notes will help me to decide whether it is worth to download and replace the old one.

I've been pondering about adding a convenient auto-update feature (see https://github.com/Martchus/syncthingtray/issues/180#issuecomment-1508361539). I suppose that would then actually address the underlying problem better. If it is convenient enough to just do the upgrade then you also don't need to read release notes to figure out whether it is worth it. (And yes, sometimes a release only contains changes for a certain platform and might indeed not be worth installing elsewhere.)

**Comment by Rygle** [comment]
https://github.com/Martchus/syncthingtray/commits/master

**Comment by binarious** [comment]
I'd also like to read release notes. Wouldn't https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes be a quick win?

**Comment by Martchus** [comment]
This would not be a win at all. At least after having a brief look this tool seems rather constrained:

> Automatically generated release notes include a list of merged pull requests, a list of contributors to the release, and a link to a full changelog.

There are almost no PRs in this project because I am almost the only contributor. Nobody would review and merge PRs. It would be more meaningful to simply make up a list of the commits between one release and the previous one.

Additionally, some interesting and user-facing changes are actually happening in c++utilities and qtutilities and Qt. For instance, High-DPI support and dark mode support on Windows has improved a lot but most of the commits wouldn't show up in Syncthing's release notes - even if we'd include every single commit of this repository. However, after a brief look I couldn't find any hints that this tool would allow creating cross-repository changelogs.

---

Note that for me it is too much effort to hand-craft release notes on every release or to setup and maintain a (semi-)automated solution. Contributions are welcome (as long as they make sense) but I personally think that a post in the forums from time to time (like https://forum.syncthing.net/t/yet-another-syncthing-tray/8502/175) must be enough.
