### ISSUE TITLE
Use Plasma 6 system-wide icon theme for the plasmoid

### ISSUE THREAD

**Issue by sten0** [Martchus/syncthingtray#197]
Continuing from #121 
              > I suppose I actually needed to use the icons from the Plasma theme here (and not from the freedesktop icon theme).

It looks like this aspect is not going to be relevant in Plasma 6 anymore (see https://pointieststick.com/2023/07/26/what-we-plan-to-remove-in-plasma-6). Since it was the only improvement left to do I'm closing this issue.

_Originally posted by @Martchus in https://github.com/Martchus/syncthingtray/issues/121#issuecomment-1666602069_

**Comment by Martchus** [comment]
This is already possible like it is for Plasma 5. You just have to configure it in the settings and restart the shell.

**Comment by Martchus** [comment]
Considering https://pointieststick.com/2023/08/12/how-all-this-icon-stuff-is-going-to-work-in-plasma-6 Plasma theme specific icons are definitely going to be removed. So I don't think there's anything left to do here since support for icons from the Plasma theme was the only missing bit and it is going to be obsoleted anyways.

**Comment by sten0** [comment]
So this means that qtforkawesome will be dropped as a dependency, right?

**Comment by Martchus** [comment]
No. It will always be a dependency because one can still change at runtime which icons to use. Also, the default of using ForkAwesome stays.

Note that the mapping of ForkAwesome icons to system theme icons is also implemented on level of the Qt ForkAwesome dependency.
