### ISSUE TITLE
How to export (backup) and import (restore) configuration parameters for Windows versions

### ISSUE THREAD

**Issue by Cardice** [Martchus/syncthingtray#198]
Configuration information would like to get backup and restore functionality to enable migration on PC.

**Comment by Martchus** [comment]
The config file of Syncthing Tray is stored under `%appdata%\syncthingtray.ini` on Windows. You can also put it next to the executable. The config of Syncthing itself can be found under `%appdata%\..\Local\Syncthing` unless you've changed that to something else. Otherwise there's nothing more to backup.
