### ISSUE TITLE
Add timestamp column in the recent changes tab

### ISSUE THREAD

**Issue by wohenbushuang** [Martchus/syncthingtray#202]
Shows the timestamp in which the recent changes were happened

**Comment by Martchus** [comment]
Please use the issue template next time. (Of course you might strip it down.)

I **assume** this is about the standalone tray application because when I recall correctly the timestamp is shown in the plasmoid.

There's not that much space in the widgets-based list view for showing more information. So I'm not sure whether this will be a big win for everybody. Supposedly the column should be optional. Note that you can already few the timestamp as a tooltip by hovering over a row. Is that not good enough?

**Comment by wohenbushuang** [comment]
> Note that you can already few the timestamp as a tooltip by hovering over a row. Is that not good enough?

I didn't know this before. It's enough for me.
