### ISSUE TITLE
Syncthingtray Webview showing numbers with too many decimal places

### ISSUE THREAD

**Issue by Nutomic** [Martchus/syncthingtray#21]
A screenshot probably shows it best:

![syncthingtray](https://user-images.githubusercontent.com/1044450/44632430-f26c0780-a93f-11e8-86ff-e6a80219dba3.png)

Syncthingtray version: 0.8.1-22.91e1c2a (installed via AUR)
OS is Manjaro with KDE and latest updates installed
Qt: 5.11.1
KDE Frameworks: 5.49.0
kf5-config: 1.0

Let me know if you need any more information. I tried to collect logs, but don't know how to.

**Comment by Martchus** [comment]
I'm already aware of this issue. However, it is not an issue within my code.

I suspect the problem lies in the (old) WebKit version provided by Qt WebKit. Maybe it helps to upgrade Qt WebKit to the latest commit (there are 98 commits since alpha 2 which is the version provided by Arch Linux).

Alternatively, it is possible to use Qt WebEngine instead of Qt WebKit (see https://github.com/Martchus/syncthingtray#select-qt-module-for-webview and the comment at the top of the PKGBUILD). Qt WebEngine provides the Blink engine under the hood (fork of WebKit) which apparently doesn't has this bug.

It has recently gotten quite silent around the effort to revive Qt WebKit. Hence I'm considering to make Qt WebEngine the default for the AUR package anyways.

**Comment by Martchus** [comment]
The AUR package defaults now to Qt WebEngine since a while now. I wouldn't expect any updated to Qt WebKit anymore. Even the revived version seems dead.
