### ISSUE TITLE
Windows on arm build

### ISSUE THREAD

**Issue by xgdgsc** [Martchus/syncthingtray#218]
---

**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Is your feature request specific to a certain platform/environment? Please specify.**
Windows on arm
 
https://www.qt.io/blog/qt-for-windows-on-arm don' t know how hard it is.

**Comment by Martchus** [comment]
A valid feature request but don't expect me to work on it anytime soon.

Note that this will most likely compile (and if not only with trivial fixes) so anybody is welcome to provide builds for that architecture similar to other additional builds that are already listed in the [README's download section](https://github.com/Martchus/syncthingtray#download).

If you want to use Syncthing Tray on Windows/ARM right now then it is likely best to use the x86_64 build of Syncthing Tray in combination with the ARM build of Syncthing itself. (So basically avoid using the built-in Syncthing library so at least Syncthing itself runs natively.)

**Comment by Martchus** [comment]
See https://forum.syncthing.net/t/yet-another-syncthing-tray/8502/217?u=martchus

**Comment by xgdgsc** [comment]
![image](https://github.com/user-attachments/assets/84ecc4e5-3f43-4871-a153-057c8532254c)
Thanks. The static reports missing libzstd.dll

**Comment by xgdgsc** [comment]
Copying the file from msys2 works.

**Comment by Martchus** [comment]
I guess I'll have to dive into the CMake code again then…

Good that you've tested with the DLL from MSYS2. This way we know that the DLL is the only problem and that the executable generally works.

**Comment by Martchus** [comment]
I built a new version: https://martchus.dyn.f3l.de/repo/arch/ownstuff-experimental/os/x86_64/mingw-w64-clang-aarch64-syncthingtray-qt6-1.6.3-1-any.pkg.tar.zst (This package has the version 1.6.3 but it is actually a development build.)

This one should work (according to `llvm-objdump` the DLL is no longer linked against dynamically).

**Comment by xgdgsc** [comment]
Works fine. The last version seemed exited after one night's sleep , I will see if this one also exit.

**Comment by xgdgsc** [comment]
Also exit after one night' s sleep.

**Comment by Martchus** [comment]
I suppose it "just" crashes. It is hard to tell why. I assume the issue does not exist in the x86_64 build?

Maybe you can start it in a terminal (so you can see stdout/stderr, use either MSYS2 or the `-cli` wrapper) and enable all logging (search for logging in the README). This way we might at least be able to see what it did shortly before crashing.

Maybe you can also share your Syncthing Tray config so I could at least rule out issues relating to features you don't have enabled.

Maybe you can find an easier way to reproduce the issue, e.g. maybe suspending and resuming the system triggers the issue (without waiting a whole night)? If that's the case maybe the code to suppress notifications after the system has just been resumed is at fault.

Otherwise I'm afraid I cannot really help much with this issue as I don't have a way to reproduce it myself.

**Comment by xgdgsc** [comment]
I can use task scheduler to run it after unlock. It' s just it doesn' t auto connect after start with the auto connect option checked, I have to manually connect.

**Comment by Martchus** [comment]
Ok, so it does *not* crash or otherwise exists early. The only problem is that Syncthing Tray does not auto-connect to Syncthing when resuming from standby. Am I now getting the problem correctly?

The settings look correct for this to happen so this must be a bug then. I can try to reproduce it locally when I have time. Maybe this is related to the launcher not being able to use Boost.Process (so it uses QProcess and those code paths aren't regularly tested). It the output of Syncthing shown correctly in the launcher and in particular is the GUI listening address shown?

Note that Syncthing Tray ignores the unavailability of Syncthing the first 15 seconds (`ignoreInavailabilityAfterStart`) after the start to give Syncthing it some time and avoid an error notification. Then it'll only re-connect after 30 seconds (`reconnectInterval`) and continue to do so every 30 seconds. If you start Syncthing Tray with logging as suggested before, can you see that those connection attempts are made?

Does it work when you disable `considerLauncherForReconnect`? Then Syncthing Tray will of course needlessly re-connect while Syncthing is not launched anyway and notifications won't be suppressed. However, when it works with `considerLauncherForReconnect` we know that it has something to do with the launcher.

**Comment by xgdgsc** [comment]
`considerLauncherForReconnect=false` works for me. It connects immediately after start.

**Comment by Martchus** [comment]
Ok, then `considerLauncherForReconnect` is probably broken when using `QProcess`. Did you see any log message from before the crash meanwhile? If it really always crashes after resuming from standby this should be easy to reproduce.

**Comment by Martchus** [comment]
As the build itself is provided I'm closing this issue in favor of https://github.com/Martchus/syncthingtray/issues/304.
