### ISSUE TITLE
Support custom status icons

### ISSUE THREAD

**Issue by BreadYogurt** [Martchus/syncthingtray#22]
I'm using the Papirus Adapta Nokto icon set on KDE Plasma and the syncthingtray applet's colors clash with the rest of my status icons.

**Comment by Martchus** [comment]
I actually do not force any particular icon theme. In the widgets based tray application the icon theme can be overridden explicitly in the config, though.

Or do you mean that my custom icons (basically the Synching icon) does not fit? Changing those is currently not possible. I actually intended to create a flat version of them and support having different sets of those custom icons. Is that what you have in mind?

**Comment by BreadYogurt** [comment]
Huh, maybe Papirus doesn't have icons set for syncthingtray. I'll look into setting that up myself.

**Comment by BreadYogurt** [comment]
Oh, yeah, reread your response and yes, I am talking about the tray icon.

**Comment by alxlg** [comment]
Is it possible to change the icon of the plasmoid via Plasma theme or Freedesktop icon theme? If yes what's the name of the icon? I can eventually add a proper flat Syncthing icon to Breeze theme.

**Comment by Martchus** [comment]
No, it is not possible to change the icons of Syncthing itself by changing the Plasma theme or Freedesktop icon them. So far only the bundled Syncthing icons are used. That is simply due to the fact that no Freedesktop icon theme I know has icons for Syncthing.

But if you would add Syncthing icons for the different states to the Breeze theme I would extend my code to make use of them and only use the bundled icons as fallback.

I don't like using resources from the Plasma theme, though. That's because the same code is also used for the generic, Qt Widgets based GUI which should not depend on anything from Plasma.

I'm also not sure whether I actually like that the "idle" state is green. Making it green was my own choice some time ago but I actually don't like it that much myself because it makes the tray icon by default green and a light blue would likely be more appropriate. So if you or somebody else likes to come up with different icons feel free to change the colors. I would only insist that the different overall states (idle, scanning, syncing, warning, error) are distinguishable *somehow* and that the error icons is red.

**Comment by Martchus** [comment]
I made the icon color now customizable. One can set both gradient colors individually. Assigning the same color makes it flat.

I think that is a good solution because you don't need to add an icon for each state to the icon theme. And Syncthing Tray does not need to rely on that there is no state missing. Besides, this way the user can pick colors which match the individual color palette best.

![Screenshot_20190519_181602](https://user-images.githubusercontent.com/10248953/57985027-379e0f80-7a62-11e9-918d-60478f46bc77.png)

**Comment by Martchus** [comment]
Closing because one can configure the general icon theme as well as the color of custom icons.
