### ISSUE TITLE
Recent changes are sometimes not fully populated or empty

### ISSUE THREAD

**Issue by truthsword** [Martchus/syncthingtray#230]
On my laptop (Win10), the Recent Changes view is always empty, However my desktop (Win11) shows all sync activity, including laptop/desktop sync.

Have I overlooked a setting on my laptop? Thank you!

**Comment by Martchus** [comment]
No; it is probably a bug. I've actually noticed myself that very rarely the recent changes view is not populated as expected. However, since it was hard to reproduce and I couldn't spot any obviuos mistake in the code I haven't done anything about it. It could theoretically also be a problem in Syncthing itself.

Note that it normally helped to re-connect forcefully (using the button at the bottom in the connection settings).

**Comment by truthsword** [comment]
Thanks, the reconnect refreshed the view.

**Comment by Martchus** [comment]
Ah, and I was going to write: If the problem is persistent in your case (so the re-connect does not help) then I wonder whether the recent changes are also missing in Syncthing's official UI in your case.

I guess I'll reopen the issue to give figuring this out one more shot.
