### ISSUE TITLE
Ability to ignore "folder missing" errors for specific folders

### ISSUE THREAD

**Issue by jcotton42** [Martchus/syncthingtray#234]
**Relevant components**
Standalone tray application (based on Qt Widgets)

**Is your feature request specific to a certain platform/environment? Please specify.**
No

This is a very niche request, but one of my Syncthing folders is synced to an encrypted disk image that I only mount and unlock when I need access to those files. This works to keep them protected, but also means that the Syncthing Tray icon is red 99% of the time.

Would you consider adding the ability to ignore "folder missing" errors for a specific folder, so that the icon's color can be green when that's the only folder out of sync/missing.

![image](https://github.com/Martchus/syncthingtray/assets/5257450/6bf48179-06a5-48df-a5a0-2d3db51ef45a)
Here "Secure Documents" is the one being synced into the encrypted disk, I'd like it's "missing" status to be ignorable for the purposes of whether or not the tray icon is red.

**Comment by Martchus** [comment]
> one of my Syncthing folders is synced to an encrypted disk image that I only mount and unlock when I need access to those files.

I actually do the same. However, I usually keep the folder paused and only unpause it after mounting (and pause it again before umounting). This is an easy and clean way to avoid the error state.

The feature request generally makes sense as well. I suppose the easiest would be to allow entering an ignore regex. (Making a normal selection would be a bit more work because as for as Syncthing Tray is so far concerned folders "come and go" as they are created/removed in Syncthing itself. So Syncthing Tray has so far no persistent configuration for folders and having persistent configuration for folders outside of Syncthing's own config would be a bit weird because then some settings would be stored server side and affect all clients and some settings would be client-side affecting only a specific client.)

**Comment by jcotton42** [comment]
I'll give the pausing thing a shot, thanks for the idea.
