### ISSUE TITLE
Unable to install from AUR: syncthingtray 1.5.3-1

### ISSUE THREAD

**Issue by coffebar** [Martchus/syncthingtray#258]
> :: Synchronizing package databases...
>  core is up to date
>  extra is up to date
>  community is up to date
>  ownstuff is up to date
> Sync Explicit (1): syncthingtray-1.5.3-1
> resolving dependencies...
> looking for conflicting packages...
> 
> Package (1)             New Version  Net Change  Download Size
> 
> ownstuff/syncthingtray  1.5.3-1        2.52 MiB       0.71 MiB
> 
> Total Download Size:   0.71 MiB
> Total Installed Size:  2.52 MiB
> 
> :: Proceed with installation? [Y/n]
> :: Retrieving packages...
>  syncthingtray-1.5...   729.7 KiB  1208 KiB/s 00:01 [###########################] 100%
> (1/1) checking keys in keyring                      [###########################] 100%
> (1/1) checking package integrity                    [###########################] 100%
> error: syncthingtray: signature from "Martchus <martchus@gmx.net>" is unknown trust
> :: File /var/cache/pacman/pkg/syncthingtray-1.5.3-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
> Do you want to delete it? [Y/n] n
> error: failed to commit transaction (invalid or corrupted package (PGP signature))
> Errors occurred, no packages were upgraded.
>  -> error installing repo packages

**Comment by coffebar** [comment]
`sudo pacman-key --refresh-keys` didn't help

**Comment by Martchus** [comment]
It looks like you're not installing this package from the AUR but from my binary repository.

I had to update my PGP key yesterday because it had expired. So you need to follow steps on https://martchus.no-ip.biz/repo/arch/ownstuff to import the key again.

The following should do it:

```
pacman-key --delete B9E36A7275FC61B464B67907E06FE8F53CDC6A4C  # delete old version of the key
pacman-key --keyserver keyserver.ubuntu.com --recv-keys B9E36A7275FC61B464B67907E06FE8F53CDC6A4C  # download new version of key from a server known to already have the latest version
pacman-key --lsign-key B9E36A7275FC61B464B67907E06FE8F53CDC6A4C  # trust new version
```

(You probably don't need to delete the old version of the key. It worked without doing that on one of my systems. However, on another machine it didn't work for some reason I couldn't figure out yet. There it worked after deleting the old key first.)

**Comment by coffebar** [comment]
**delete** and **lsign** was necessary for me

**Comment by Martchus** [comment]
Ok, good to know. (I believe that `--lsign-key` is necessary is expected considering the key is self-signed.)
