### ISSUE TITLE
Building error "c++utilities" on kubuntu 18.04.1

### ISSUE THREAD

**Issue by lyndhurst** [Martchus/syncthingtray#26]
Hi, I tried building the application from source but failed.

I have little experience with building with cmake, I am on a fresh kubuntu 18.04.1 install. I have installed clang, but when issuing the cmake command, I get a c++utilities error, I pasted the output at the end.

I tried following your link on the build instructions page regarding c++ utilities, but I do not really understand how to build that part. It seems I have to point to the final installation folder, which I have no idea which it is, and to the "project folder" I guess it is the syncthingtray source I am trying to build...

I tried the AppImage, but it looks nothing like the screenshots, and do not seem as integrated as your built application (Dolphin, plasmoid and such ...)

I am sorry to waste your time if the building process is beyond my skills, and will wait for a deb package or a ppa :) Thank you.

**Here is the terminal error output:**

CMake Error at connector/CMakeLists.txt:50 (find_package):
  By not providing "Findc++utilities.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "c++utilities", but CMake did not find one.

  Could not find a package configuration file provided by "c++utilities"
  (requested version 4.16.0) with any of the following names:

    c++utilitiesConfig.cmake
    c++utilities-config.cmake

  Add the installation prefix of "c++utilities" to CMAKE_PREFIX_PATH or set
  "c++utilities_DIR" to a directory containing one of the above files.  If
  "c++utilities" provides a separate development package or SDK, be sure it
  has been installed.

**Comment by Martchus** [comment]
> I tried the AppImage, but it looks nothing like the screenshots, and do not seem as integrated as your built application (Dolphin, plasmoid and such ...)

Distributing the Plasmoid and Dolphin menu would as AppImage is not possible.

---

CMake tells you what you need to do (first sentence of the last paragraph). So when invoking `cmake` to build Syncthing Tray, you need to pass the argument `-DCMAKE_PREFIX_PATH=$cpp_utilities_install_prefix` where `$cpp_utilities_install_prefix` points to the directory where c++utilities has been installed. The same applies to qtutilities.

---

But there's an easier solution. You can build Syncthing Tray, qtutilities and c++utilities in one step by following the "[Building this straight](https://github.com/Martchus/syncthingtray#building-this-straight)" instructions.

**Comment by lyndhurst** [comment]
Thanks for your reply, I did it wrong the first time around, I successfully built this time.
Need to try to buil plasmoid, and dolphin action item now..
thanks.

**Comment by Martchus** [comment]
Unless you disabled building the Plasmoid and Dolphin action, those should have been built right away. Since those are plugins which need to be loaded by `plasmashell` and `dolphin`, they need to be installed appropriately.

It is also possible to install the Plasmoid and Dolphin menu in your home directory. I usually do that for testing (see https://github.com/Martchus/syncthingtray#kde-integration). To make it find the plugin library, just set the environment variable `QT_PLUGIN_PATH` to the directory where the so files for the plugins can be found.

Maybe I should really provide Debian/Ubuntu packages :-)

**Comment by Martchus** [comment]
You can repoen the issue if you have further questions, but I'm closing it for now.

**Comment by geser2008** [comment]
> Unless you disabled building the Plasmoid and Dolphin action, those should have been built right away. Since those are plugins which need to be loaded by `plasmashell` and `dolphin`, they need to be installed appropriately.
> 
> It is also possible to install the Plasmoid and Dolphin menu in your home directory. I usually do that for testing (see https://github.com/Martchus/syncthingtray#kde-integration). To make it find the plugin library, just set the environment variable `QT_PLUGIN_PATH` to the directory where the so files for the plugins can be found.
> 
> Maybe I should really provide Debian/Ubuntu packages :-)

That's will be awesome!!!

**Comment by Martchus** [comment]
Ok, but that issue is not about providing Debian/Ubuntu packages. So I'm closing it again unless there are further questions regarding that build failure.

By the way, there's already a bug for creating a Debian package: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884575  
They never took the effort, though.
