### ISSUE TITLE
Uninstall option?

### ISSUE THREAD

**Issue by slrgt** [Martchus/syncthingtray#260]
There doesn't seem to be an option to uninstall the application on windows. It doesn't appear in the windows Add or Remove Programs section or have instructions on uninstalling it in the github readme

**Comment by Martchus** [comment]
Synching Tray doesn't come with an installer (just like Synching itself). That means there's nothing to be uninstalled. Just delete the exe file and perhaps make sure autostart is disabled before (to avoid a dangling entry). You can also delete the configuration of Synching and Syncthing Tray, see the Syncthing documentation and the README in the repo for the locations.

**Comment by Martchus** [comment]
I added a README section. That should cover this issue.

**Comment by slrgt** [comment]
@Martchus how do we uninstall it so we can get the setup wizard though?

**Comment by Martchus** [comment]
You can delete the configuration, see my previous explanation. You can also just open the wizard from the settings dialog again (button at the top-right corner) at any time.

**Comment by mokahless** [comment]
Without this issue fixed, I can't roll this out to my "user" friends. They wouldn't know the first thing about manually removing the changes made here for autostart and deleting the right files.

Can we re-open this issue? I recommend simply put an uninstall.bat file in the folder or something?


Edit: I gave up on getting syncthingtray working (default install is not built with built-in web browser for basic viewing?) and I'm pretty sure my inability to properly remove everything is breaking my new install of synctrayzorv2

Edit2: Issue was with syncthing in appdata. Couldn't delete all the files from that folder due to file locks, despite having both closed and deleted syncthing tray. Using the synctrayzorv2 uninstaller removed everything and I got that program reinstalled and working.
