### ISSUE TITLE
[Windows 10] Disconnected after hibernation

### ISSUE THREAD

**Issue by Manuel-S** [Martchus/syncthingtray#27]
Hey, I really like this tool and just wanted to note this minor issue:

after booting from hibernation, syncthingtray always opens up a notification that it can't connect. I've set the reconnect interval quite high so it only shows up once, on default it can show up several times before the connection is re-established.

Maybe there is a way to detect hibernation/sleep mode to prevent those messages from popping up in that case?

**Comment by Martchus** [comment]
I'm aware of this issue and implemented a solution in the way you described for systemd-based platforms (basically all modern GNU/Linux distributions).

It is unlikely that I take the effort to add Windows support for this feature. Contributions in this regards are welcome of course.

As a workaround you can of course completely disable that notification.

**Comment by Martchus** [comment]
I implemented detection of sleep/hibernation under Windows like it has already been done for systemd-based systems.

Judging by some debug-logging the detection really works. It should also help to supress notifications (unless Syncthing would not be responsible for too long; the grace period is configurable in the settings). I wasn't really able to test it because on my system I couldn't see this notification anymore anyway. Maybe the connection is not interrupted anymore due to this or at least not in all cases. Either way, this issue should be resolved.
