### ISSUE TITLE
I don't understand

### ISSUE THREAD

**Issue by allanonmage** [Martchus/syncthingtray#272]
I'm a long time Windows user, and am coming from SyncTrayZor.  I've tried out your software and I don't get it.  I've never been able to make Linux work for me, get hired as a dev, nor make friends in the dev community.  Maybe I'm missing something though, so I'm here to figure this out.

I'm using this version: https://github.com/Martchus/syncthingtray/releases/download/v1.5.4/syncthingtray-1.5.4-x86_64-w64-mingw32.exe.zip

- Your software doesn't have a webview of the Syncthing web UI, but does have it's own UI that doesn't appear to actually do anything regarding setting up Syncthing things.  Getting to the Syncthing UI to do Synchthings is more cumbersome than saving a bookmark.
- You are so over-articulate and over-technical on your github, download page, and in the UI of the program that I have no idea what you are saying most of the time.
- Endless referrals to other things is a terrible way to do documentation.  I had to go to 3 or 4 different pages to figure out why the executable wasn't working.  Turns out I didn't have the GUI version, even though it looked like it was on the releases page.
 - Portable software does not make files outside of it's own directory.  You're using the concept of a home directory (APPDATA), which is what installed software does.  Portable software does not.  These may be Windows conventions, which is why they are probably new to you.  You're not the first Linux project I've seen make Windows software like this.  It's categorically bad.  Portable software means you copy it's folder and move it, and all the settings with it.  Not track down 3 different APPDATA folders worth of settings.

So, I have to ask, what's the point?  Are you a Linux user that just so happened to compile the project for Windows?  I don't see the value add for your software vs just running the service in the background and connecting to the web GUI.

Most importantly, I can't recommend this to nontechnical people, which means I can't install this on their machine for us to use together, because guiding them through it over the phone would be a nightmare.  I'm the dev and techy guy in my circle, and I can't figure out your software, so it's certainly useless to them.

**Comment by Martchus** [comment]
> Your software doesn't have a webview of the Syncthing web UI, but does have it's own UI that doesn't appear to actually do anything regarding setting up Syncthing things. Getting to the Syncthing UI to do Synchthings is more cumbersome than saving a bookmark.

It has a web view but not the binaries I provide for Windows as I'm not going to distribute a web browser. You can make it use the app mode of e.g. Edge in the settings.

> You are so over-articulate and over-technical on your github, download page, and in the UI of the program that I have no idea what you are saying most of the time.

Too bad but I'm not going to dumb-down the wording. I already provide a less technical overview on [the website](https://martchus.github.io/syncthingtray) but this is as "dumb" as it gets.

> Endless referrals to other things is a terrible way to do documentation. I had to go to 3 or 4 different pages to figure out why the executable wasn't working. Turns out I didn't have the GUI version, even though it looked like it was on the releases page.

I know but the effort I can spend on documentation is limited. A single, simple markdown document makes things easier on my side.

> Portable software does not make files outside of it's own directory. 

True - but like Syncthing itself Syncthing Tray is not portable software in that sense. Not having an installer does not mean it is portable software. (Just for the record: There is a way to make it portable, see https://github.com/Martchus/syncthingtray?tab=readme-ov-file#location-of-the-configuration-file.)

> So, I have to ask, what's the point? Are you a Linux user that just so happened to compile the project for Windows? I don't see the value add for your software vs just running the service in the background and connecting to the web GUI.

To have a tray icon. To *not* have a terminal window around. Quick access to most important features without opening the web UI. If you don't value/need any of these you are indeed better off just using Syncthing on its own.

> Most importantly, I can't recommend this to nontechnical people, which means I can't install this on their machine for us to use together, because guiding them through it over the phone would be a nightmare. I'm the dev and techy guy in my circle, and I can't figure out your software, so it's certainly useless to them.

Probably true but that was never the goal of this software and still is not the goal. I have never stated anywhere that this software is targeting nontechical people so I am seriously wondering how you could ever come to that impression. I mean - you state it yourself - my wording clearly suggest otherwise.

Note that this is really not a "bug". If this is not the type of software you're seeking you should probably look elsewhere. So I'm closing this issue as this is nothing I will work on.

**Comment by Martchus** [comment]
One more remark on:

> and am coming from SyncTrayZor

I had checked out SyncTrayzor and QSyncthingTray before I started to create Syncthing Tray. I did not just use them (or contributed to them) because they clearly had a different focus than what I had in mind. It is unfortunate that SyncTrayzor and QSyncthingTray have been (more or less) abandoned and now people migrate to Syncthing Tray and expect it would be a replacement which it was never meant to be.

**Comment by sten0** [comment]
@allanonmage You're probably looking for #134 :)  There's also the "paradox of knowledge".  In most cases, this means that people who have knowledge communicate as if others have that knowledge, unless they have the communications/teaching base-skill (usually considered a "soft" skill in the sciences).  As you know, the result is impenetrable and not particularly useful user-facing documentation.  This is why documentation writers (and teams) are so, *so* important.

Re: "portable"...  It seems like you're using this word in the Windows-specific way that emerged sometime after the release of Windows Vista, or possibly Windows XP.  Ie: copy a foo.exe to a USB stick, bring that USB stick from computer to computer, run the software without installing it, and any configuration also ends up on the USB stick.  This wasn't called "portable software" during the MSDOS era when people would do this with floppies--to say it was is to advocate for an ignorant retcon.

When speaking to developers, and in particular if you'd like to find work as a dev, you'll be more successful (and will make more friends) if you the well-recognised understanding of "portable software" https://en.wikipedia.org/wiki/Software_portability  It's also worth learning Windows NT (and thus a bit of BSD) history.  Finally, if you care about networking and the internet at all, one should note that it is fundamentally multiplatform and UNIX-based.  Demonstrate industry knowledge and you'll get the high-paying job.

**Comment by Martchus** [comment]
Yes, they were using "portable" in a Windows-specific way. That's also why I gave a Windows-specific answer - but I like that you point out https://en.wikipedia.org/wiki/Software_portability.
