### ISSUE TITLE
Icons rendering in plasmoid has lower quality than the tray application

### ISSUE THREAD

**Issue by mrpink17** [Martchus/syncthingtray#282]
**Relevant components**
* [ ] Standalone tray application (based on Qt Widgets)
* [x] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* gcc 14.2.1+r134+gab884fffe3fc-1
* glibc 2.40+r16+gaa533d58ff-2
* syncthingtray-qt6 1.6.2-1
* qt6-base 6.7.2-2
* c++utilities 5.26.1-1
* qtutilities-qt6 6.14.3-1
* Operating System: Arch Linux 
* KDE Plasma Version: 6.1.5
* KDE Frameworks Version: 6.6.0
* Qt Version: 6.7.2
* Kernel Version: 6.10.10-arch1-1 (64-bit)
* Graphics Platform: Wayland

**Bug description**
The rendering of some icons in plasmoid is not as good as in tray application

### Plasmoid
![plasmoid-app](https://github.com/user-attachments/assets/72dd613e-0cac-421f-a29c-8b1709a89ce0)

### Tray application
![tray-app](https://github.com/user-attachments/assets/28ae452a-b81a-4930-9a0b-e4db95d88589)

**Comment by Martchus** [comment]
Looks like the icon rendering is broken in the Plasmoid. For me the icon rendering *generally*¹ works within the Plasmoid as well. Does it work under X11?

---

¹ Today I noticed that Plasma falls back to software rendering on my Arch system when using Wayland. With this the entire shell looks quite broken when it comes to icons. Switching to X11 helped but I'm wondering what's wrong with Plasma on Wayland since the last update. The issue I am experiencing is definitely not specific to this Plasmoid but means I can currently not develop/test under KDE/Wayland. And under KDE/X11 I cannot reproduce any rendering issues with the Plasmoid.

**Comment by mrpink17** [comment]
No, Wayland and X11 look the same

**Comment by Martchus** [comment]
Looks like the Wayland-related issue I mentioned is actually more NVIDIA-related and tracked on https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/issues/80.

I can reproduce the issue you've mentioned when enabling the setting to prefer system icons over ForkAwesome icons. So as a workaround I suggest you disable this setting. You'll need to restart `plasmashell` for this to have an effect.

**Comment by Martchus** [comment]
I have no idea why the icon rendering doesn't work in this case. I tried to play around with the rendering code but it looks like it might be a Qt bug.

**Comment by mrpink17** [comment]
I can confirm it used to work, but it was many months ago. I feel it happened after upgrading the synchthingtray package, not a Qt upgrade, but I'm not 100% sure

**Comment by Martchus** [comment]
The relevant code on my side is actually this line in `qtforkawesome`: https://github.com/Martchus/qtforkawesome/compare/v0.1.0...v0.2.1#diff-bbdda2a0a28454037de0dc03c0077fd4b526a8b0027652e04e8d3e88c70ad8ecR151

But it hasn't changed for quite a while in it is merely using `QIcon::pixmap()`.

**Comment by Martchus** [comment]
Looks like this is still broken on Qt 6.7.3.
