### ISSUE TITLE
feat: Allow Gnome users to open popup

### ISSUE THREAD

**Issue by xieve** [Martchus/syncthingtray#284]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Is your feature request specific to a certain platform/environment? Please specify.**
Gnome 46, probably also derivations, earlier and later versions.

**Is your feature request related to a problem? Please describe.**
I'm a Gnome user, and I want to use the nice popup menu this project provides. The only actively maintained tray extension (which is also linked in this project's README) [will not support secondary actions](https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/25) since Gnome-Shell does not.

As mentioned in the README, this means that the context menu will be available, while the popup will not. However, contrary to what (I think) the README suggests, this problem applies to all Gnome installations.

**Describe the solution you'd like**
I would like syncthingtray to open the popup instead of the context menu when running on Gnome by default. This would match the behavior of the system panels.

**Describe alternatives you've considered**
It is probably possible to "fix" this on the extension/DE side, but I myself have no time or energy to develop a new tray or maintain a fork. I have tried the extensions "TopIconsFix" and "Tray Icons Reloaded", they were both less usable than the AppIndicator one.

In case the DE detection were not wanted or feasible, I would like this to be a config option.

Even simpler would be a context menu item named "Show" that shows the popup. Still two clicks instead of one, but at least it would be accessible. This is how trayscale handles it.

I will as a workaround set a keyboard shortcut for `--trigger`, but that is not ideal to me.

**Additional context**
![image](https://github.com/user-attachments/assets/9a72b282-01d6-48ce-8d9d-6c72dba6104e)
Current left- and right-click behavior.

![image](https://github.com/user-attachments/assets/e85ab962-481d-4d2e-b30a-66e01ccc5141)
Trayscale has a "Show" menu item.

(Sorry for the huge pictures, idk how to make them smaller in Markdown.)

**Comment by Martchus** [comment]
> As mentioned in the README, this means that the context menu will be available, while the popup will not. However, contrary to what (I think) the README suggests, this problem applies to all Gnome installations.

I wrote it this way based on user feedback. I don't have the time to test it myself on various desktop environments. However, what you describe really sounds like the Ubuntu-flavoured GNOME shell is not special in that regard. (I suppose when I tested this ages ago under purse GNOME things were still different.)

> I would like syncthingtray to open the popup instead of the context menu when running on Gnome by default. This would match the behavior of the system panels.

You will run into positioning issues on Wayland (which you probably use). So this is only of limited usefulness. Of course if you can live with the popup spawning in the middle of the screen we can discuss this further :-)

> I would like syncthingtray to open the popup instead of the context menu when running on Gnome by default. This would match the behavior of the system panels.

The behavior you describe already works on other platforms. I don't think I did a programming mistake on my side which would prevent it to work under GNOME. This is rather a limitation of GNOME and the particuar extension for tray icon support. So I'm afraid you'll have to create an issue about this on the issue tracker of the extension.

> It is probably possible to "fix" this on the extension/DE side, but I myself have no time or energy to develop a new tray or maintain a fork. I have tried the extensions "TopIconsFix" and "Tray Icons Reloaded", they were both less usable than the AppIndicator one.

If people on the extension/DE side are sane enough, they consider a contribution to avoid this limitation. So you don't have to fork.

> In case the DE detection were not wanted or feasible, I would like this to be a config option.
>
> Even simpler would be a context menu item named "Show" that shows the popup. Still two clicks instead of one, but at least it would be accessible. This is how trayscale handles it.

I suppose adding such an item when GNOME shell is detected or via config option would be possible. I think that'll actually be the best one could do from Syncthing Tray's side considering the limitations of the extension.

> Trayscale has a "Show" menu item.

I supose this tool also only shows the same context menu regardless whether you do a left- or right-click? From its GitHub repo it looks like the "Show" action of this tool opens a normal window and not a popup. Note that this is supposedly the conventional behavior - and not showing another popup window that is not even positioned correctly as such. That's why it probably makes more sense to stick to "Open Syncthing" by default and really only show a 2nd "Open Syncthing Tray" action if configured.

---

I am currently working on a fully-featured Qt Quick based UI for Android - mainly for the fun of it as there's of course already an app. There's still a lots of development to do. However, I am contemplating of also adding this full-featured UI on desktop versions as well so you could configure to show a native UI instead of the web-based UI when clicking any "Open Syncthing" actions/buttons that so far only showed the web-based UI. The web-based UI would still be accessible on a dedicated page within this native UI. This Qt Quick based UI will still look rather simple and similar to the "popup UI" because I'm optimizing it mainly for mobile use and will reuse a lot of existing code. If this is implemented it'll also solve this problem. You would still not get the "popup UI" but probably something even better and also something more conventional to show on such a context menu option.

**Comment by Martchus** [comment]
Considering the screenshot on https://tailscale.com it becomes apparent that the Trayscale app you mentioned is also very limited compared to what's possible on other platforms (presumably Mac OS on that screenshot). It is a shame that the GNU/Linux desktop is such a limiting platform these days when it once was one of the platforms you do the most on.

**Comment by xieve** [comment]
Damnit, reading can be hard sometimes. The AppIndicator Extension's README says:

>Double clicking an icon will activate the application window (if implemented by the indicator).

This works flawlessly. Sorry for bothering you. The Wayland positioning issue still remains, although ubuntu/gnome-shell-extension-appindicator#298 mentions that Wayland has the concept of "Positioners" for this. I assume that syncthingtray is currently running through XWayland?

**Comment by xieve** [comment]
Update: Running under XWayland actually introduces another bug: The only ways to close the popup seem to be either to click the empty space between the "Stop" and the "About" ("i") button, or *clicking* another XWayland window. Focusing or clicking a Wayland window will not close it. Perhaps there is a way to at least mimic the behavior I was experiencing when running natively under Wayland, where it would instantly close the moment I focused another window. Alternatively, detecting the mouse leaving and closing after a short period of time sounds very easy to implement to me (this would have to be opt-in though).

**Comment by Martchus** [comment]
> Damnit, reading can be hard sometimes. The AppIndicator Extension's README says:

You're not the only one who missed that. I know at least one other user who ran into the problem and after that I updated the README of Syncthing Tray adding the paragraph about limitations. I suppose that's the price you have to pay for using software that needlessly breaks with conventions like GNOME-related software. I updated the README in Syncthing Tray once more to avoid spreading wrong information.

> The Wayland positioning issue still remains, …

I will not respond to any of this because there's nothing more I can add that I haven't already said in the README or other issues on GitHub. If you believe this can be implemented in Syncthing Tray, prove me wrong and provide a PR :-)

I am not going to spend any more effort on this at this point, though. If Wayland developers decide to break common features by not providing APIs that are established on other platforms that is not my problem. Users will have to live with the breakage if they decide to use Wayland that intentionally limits these things.

(Luckily the Plasmoid for KDE is not affected by this. The fully-featured Qt Quick UI will also help with this in the future like I have already mentioned.)
