### ISSUE TITLE
Yellow icon with exclimation point saying there are notifications available. But I can't find them anywhere

### ISSUE THREAD

**Issue by snab43** [Martchus/syncthingtray#285]
My Syncthing Tray icon is green with an exclamation point. When I hover it says "Notifications available". But I can't find where these notifications are? I've looked everywhere and can't find any notifications to view or dismiss. Is it because one of my remote devices is disconnected? I have 3 devices syncing together and they're not always on at the same time.

Very minor issue, but I'm just a bit baffled by this.

**Comment by Martchus** [comment]
Are you using the Plasmoid or the Qt Widgets based version? A screenshot would help as well. It would generally be helpful to not completely dismiss the issue template - it is there for a reason.

**Comment by snab43** [comment]
Sorry about that! I read through it but figured it wasn't too relevant to my very minor issue.

---

**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Is your feature request specific to a certain platform/environment? Please specify.**
Windows 10

**Is your feature request related to a problem? Please describe.**
Persistent "Notifications available" and green icon

**Describe the solution you'd like**
Where to find the notifications and how to dismiss or attend to them.

**Describe alternatives you've considered**
n/a

**Additional context**
![image](https://github.com/user-attachments/assets/c1184886-c408-4eb6-8305-de438d8f3edf)

![image](https://github.com/user-attachments/assets/b3eaf328-52ec-42d2-a3c2-6b4c0c349a3d)

![image](https://github.com/user-attachments/assets/49cd6062-8081-4c14-ab10-77e1ef3af4e4)

**Comment by Martchus** [comment]
Ok - so you could even reproduce the issue again and recreate screenshots.

I've just tested the behavior of Syncthing Tray on notifications. There are definitely some limitations that I should probably fix. However, if there's a notification (according to Syncthing Tray) it will allow you to show it by clicking on the Syncthing Tray icon itself and within the GUI of Syncthing Tray itself you should be able to see a dropdown menu regarding notifications. You can "Show" and "Dismiss" them. This part definitely worked in my tests (even though "Show" also dismissed them at the same time but I guess that's how I initially designed it).

Note that the web GUI might not show the notifications anymore because they are already dismissed. Unfortunately you'll have to dismiss the notifications in Syncthing Tray additionally at this point. That's one of the limitations.

I suppose I'll rework the notification handling code so it will always show the exact same set of notifications that the web GUI does instead of cutting corners. Note that it'll be never perfect because Syncthing has no event API for notifications. So it will always take a little bit of time for the state of notifications to become in-sync between different GUIs.

**Comment by snab43** [comment]
I appreciate you looking into this! Also sorry, I'm colorblind and have trouble with green/yellow lol.

Yeah it was that yellow icon for a few days, but I just checked today and it's back to normal. Maybe it was a computer restart, can't remember anything I did differently:
![image](https://github.com/user-attachments/assets/a9d66380-fbb7-4459-945f-d98725ce0d2b)

I couldn't see any notifications on the Syncthing Tray settings, personally. When I click on the icon it brings up a Chromium window for Syncthing. In the settings I've never seen any drop downs.

But regardless, it seems like you may understand what's going on and I really appreciate the help again! Sorry for my initial lack of info, hopefully this was a helpful thread!

**Comment by Martchus** [comment]
> Also sorry, I'm colorblind and have trouble with green/yellow lol.

No problem; I've just felt compelled to correct this. Note that you could configure more distinctive colors in the settings - although the exclamation mark is probably distinctive enough.

> I couldn't see any notifications on the Syncthing Tray settings, personally.

I didn't mean the settings dialog but the UI shown in [this screenshot](https://github.com/Martchus/syncthingtray?tab=readme-ov-file#qt-widgets-based-gui-under-windows-11).

> When I click on the icon it brings up a Chromium window for Syncthing.

If you're not getting the mentioned UI by clicking on the icon you have probably configured this in the settings. In this case you really won't have a way of dismissing notifications because even when doing this in the web-based UI Syncthing Tray will still show them.

However, I've just pushed changes on the master branch that will remove this limitation. So dismissing notifications in the web-based UI will also lead to the yellow/exclamation icon go away. It might take up to 30 seconds, though. (Depends on the polling interval for errors.) So I hope the next version will be an improvement in that regard.

---

Note that one can easily play with notifications/errors by posting them manually via a command like this:

```
curl -X POST -H "Authorization: Bearer $api_key" http://localhost:8080/rest/system/error -d 'Test notification'
```
