### ISSUE TITLE
Syncthingtray Plasmoid 1.6.2 crashes plasmashell 6.1.5 when trying to open WebView

### ISSUE THREAD

**Issue by eugenesan** [Martchus/syncthingtray#287]
**Bug description**
Syncthingtray Plasmoid crashes plasmashell when trying to open WebView.
Standalone Syncthingtray with SysTray works as expected.
Configuring external WebView (Default Browser) works as expected.

Also, when using syncthingtray without plasmoid;
If WebView configured as hidden, SystemTray UI opens as a clear/transparent window.

Inspecting plasmashell crash dump didn't contain anything useful.

**Relevant components**
* [ ] Standalone tray application (based on Qt Widgets)
* [x] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `cpp-utilities-5.26.1`, `qtutilities-6.14.3`, `qtforkawesome-0.2.1`, `syncthingtray-1.6.2`
* Qt version: `6.6.2`
* Plasma version: `6.1.5`
* C++ compiler (name and version): `gcc 14.2.0-4ubuntu2`
* C++ standard library (name and version): `libstd 14.2.0-4ubuntu2`
* Operating system (name and version): `Kubuntu 24.10`

**Steps to reproduce**
1. Install syncthingtray-kde-plasma packages
2. Add  plasmoid using "Add Widget" UI or enabling it using SystemTray "Entries" UI.
3. Configure the app with default values.
4. Open Plasmoid UI from the panel
5. Press Syncthing button to open WebView
6. Most of the time Plasmashell crashes, 1/3 of the time hangs for a long time.

**Expected behavior**
WebView windows opens and nothing crashes

**Screenshots**

**Additional context**
All packages were ported to Qt6/KF6 following PKGBUILDs as a template.

Build logs are available here:

https://launchpadlibrarian.net/754065274/buildlog_ubuntu-oracular-amd64.martchus-cpp-utilities_5.26.1-1~eugenesan~oracular1_BUILDING.txt.gz

https://launchpadlibrarian.net/754072998/buildlog_ubuntu-oracular-amd64.martchus-qtutilities_6.14.3-1~eugenesan~oracular5.3_BUILDING.txt.gz

https://launchpadlibrarian.net/754096499/buildlog_ubuntu-oracular-amd64.martchus-qtforkawesome_0.2.1-1~eugenesan~oracular2.1_BUILDING.txt.gz

https://launchpadlibrarian.net/754118938/buildlog_ubuntu-oracular-amd64.syncthingtray_1.6.2-1~eugenesan~oracular2.1_BUILDING.txt.gz

**Comment by Martchus** [comment]
This is most likely a bug in a dependency or downstream packaging because I can only say that the built-in web view (via Qt WebEngine) works just fine for me on a current Arch Linux and Tumbleweed system (using the standalone tray application and using the Plasmoid).

Does the standalone tray application work in your environment? Do other applications that use Qt WebEngine work on your system? What's logged on stdout/stderr of `plasmashell` (or the standalone tray application in case you can reproduce the issue with it as well)? Is a coredump available? But as mentioned, it is most likely a bug somewhere in the software stack of Qt WebEngine provided by your distribution so there's likely not much I can do anyway.

**Comment by eugenesan** [comment]
Standalone app + tray works with the caveat that if WebView is configured as hidden, tray UI won't open properly after WebView was opened once. Disabling hiding WebView fixes the issue instantly.

This what appears in user log when syncthing button is pressed and plasmashell crashes:
```
Oct 14 14:41:43 vmsan plasmashell[17191]: LaunchProcess: failed to execvp:
Oct 14 14:41:43 vmsan plasmashell[17191]: /usr/lib/qt6/libexec/QtWebEngineProcess
Oct 14 14:41:43 vmsan plasmashell[17192]: LaunchProcess: failed to execvp:
Oct 14 14:41:43 vmsan plasmashell[17192]: /usr/lib/qt6/libexec/QtWebEngineProcess
Oct 14 14:41:44 vmsan systemd[11114]: plasma-plasmashell.service: Main process exited, code=dumped, status=5/TRAP
Oct 14 14:41:44 vmsan systemd[11114]: plasma-plasmashell.service: Failed with result 'core-dump'.
Oct 14 14:41:44 vmsan systemd[11114]: plasma-plasmashell.service: Consumed 19.802s CPU time, 457M memory peak.
```

This what appears when plasmashell starts:
```
Oct 14 14:41:47 vmsan plasmashell[17206]: file:///usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/main.qml:162:21: QML KSortFilterProxyModel: Binding loop detected for property "sourceModel"
...
Oct 14 14:41:47 vmsan plasmashell[17206]: qml: SystemTray ItemLoader: Invalid state, cannot determine source!
Oct 14 14:41:48 vmsan plasmashell[17206]: QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0
...
Oct 14 14:41:18 vmsan plasmashell[16681]: file:///usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/main.qml:18:25: QML FullRepresentation: Binding loop detected for property "implicitWidth"
Oct 14 14:41:18 vmsan plasmashell[16681]: file:///usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/main.qml:18:25: QML FullRepresentation: Binding loop detected for property "implicitWidth"
Oct 14 14:41:18 vmsan plasmashell[16681]: file:///usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/main.qml:18:25: QML FullRepresentation: Binding loop detected for property "implicitWidth"
Oct 14 14:41:18 vmsan plasmashell[16681]: file:///usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/main.qml:18:25: QML FullRepresentation: Binding loop detected for property "implicitWidth"
```

Crash Dump:
[plasmashell.1000.crash.zip](https://github.com/user-attachments/files/17369691/plasmashell.1000.crash.zip)

**Comment by Martchus** [comment]
```
Oct 14 14:41:43 vmsan plasmashell[17191]: /usr/lib/qt6/libexec/QtWebEngineProcess
```

That makes it really look like an issue not caused by Syncthing Tray but rather by Qt WebEngine. Considering the standalone app works we know that Qt WebEngine is not completely broken on your system, though. (Although the hiding-feature is really supposed to work - and it also does on my systems using the standalone tray application and using the Plasmoid).

Maybe this is even some kind of driver issue. (I'm using mainly NVIDIA on KDE/Wayland and Intel on KDE/Wayland but I think it used to work on those systems with KDE/X11 and some other X11 sessions as well.)

I think the official web browser Plasmoid is using Qt WebEngine as well - even though probably via Qt WebEngine Quick and not Qt WebEngine Widgets as it also doesn't use a dedicated window.

**Comment by eugenesan** [comment]
I just finished a round of testing and it seems like the issue is indeed unrelated to syncthingtray.
The shell crashes with other plasmoids as well, namely Browser Plasmoid.
Thank you for your assistance in looking for a cause.

**Comment by Martchus** [comment]
Ok - then it makes probably most sense to get a stacktrace to find out where exactly the crash happens. (The coredump you attached before only listed the loaded libraries but had no stacktrace. Normally it should be visible when showing the dump with e.g. coredumpctl.)
