### ISSUE TITLE
Installer does not handle running syncthingtray

### ISSUE THREAD

**Issue by theincogtion** [Martchus/syncthingtray#291]
**Bug description**
On Windows 11 the silent updater fails if syncthingtray is running. The update is canceled with an error message

**Steps to reproduce**
Run winget upgrade syncthingtray

**Expected behavior**
Syncthingtray is closed and reopened by the installer

**Additional context**
https://github.com/marticliment/UniGetUI/discussions/2935

**Comment by Martchus** [comment]
For clarification: Syncthing Tray has no installer. This issue is referring to a community maintained winget package. 

I have no idea what "the silent updater" is. Please report issues with community maintained packaging on the corresponding issue trackers where the relevant developer(s) might actually be able to help. 

If you have a feature request to ease 3rdparty packaging this world belong here but must be stated explicitly and with relevant details.
