### ISSUE TITLE
Syncthingtray and syncthing are not in sync

### ISSUE THREAD

**Issue by sn2020aug** [Martchus/syncthingtray#294]
Syncthingtray 1.6.3 on Windows 11 reports one folder out of sync, but Syncthing does not show any out-of-sync folders at its portal.
![syncthing 1](https://github.com/user-attachments/assets/d4400094-2190-45ab-8e45-c8476108d85b)
![syncthing 2](https://github.com/user-attachments/assets/674b54f9-489b-4416-a8be-041071d05927)

**Comment by sn2020aug** [comment]
restart syncthingtray resolved the issue.

**Comment by Martchus** [comment]
I actually noticed myself that Syncthing Tray can sometimes be stuck thinking a folder is in a certain state when it is already idling. I just wasn't able to figure out why this happens. It is almost as if Syncthing itself misses an event. Normally it already helps to e.g. trigger a rescan of the folder so that some events are emitted again for it. Restarting Syncthing Tray will of course help, too.

Here it might have been useful to know whether Syncthing Tray still thinks there are out of sync items.

Let's keep this closed because without knowing more I cannot fix the problem and I'm kind of aware of it anyway.
