### ISSUE TITLE
The config file name/path is confusing

### ISSUE THREAD

**Issue by sledgehammer999** [Martchus/syncthingtray#3]
Hi, first time user of your app.

I was a bit confused on where to find the config file/name. I looked at your source and it was a bit hardto dig down to `SET_QT_APPLICATION_INFO` and where that macro is defined.

Unfortunately due to this* the config is created on Windows 7 in a location such as this:
```
C:\Users\<username>\AppData\Roaming\Martchus\Syncthing Tray.ini
```

IMO, that is very confusing and counterintuitive.
I think it should be saved under something like `syncthingtray\config.ini`. At least not under your name, because there is hardly any mental connection between it and your application in the average user's eyes.

Please, consider changing it.

*Well, this isn't a result of `SET_QT_APPLICATION_INFO`, but the way you construct the `QSettings` object.

PS: You don't specify it in the readme, but I observed that your app watches the dirs for changes and notifies syncthing to rescan them almost immediately. Is that true or a coincidence on my part?

**Comment by Martchus** [comment]
You're right. I should change the directory. It is also not nice that a space and capital letters are included in the path. In the meantime, I could also mention the path in the README.md. Note that the bad readability of the settings file is due to QSettings formatting the file which is very hard to change.

What do you want to achieve by editing the file manually? Sounds like a feature is missing.

> Is that true or a coincidence on my part?

No, just coincidence. If you want such a feature, you could use syncthing-inotify which should work well together with the tray.

**Comment by sledgehammer999** [comment]
>What do you want to achieve by editing the file manually? Sounds like a feature is missing.

I just wanted to remove any residual files/settings. I was playing around with your app and QSystemTray. But I liked yours because it is more lightweight(no builtin webview/webkit) and statically linked, without requiring an extra download of openssl. Although the GUI would need some work IMO.

>No, just coincidence. If you want such a feature, you could use syncthing-inotify which should work well together with the tray.

There is also the [QFileSystemWatcher](https://doc.qt.io/qt-5/qfilesystemwatcher.html) class. If you're interetested (and if am not bored) I might code it myself sometime into your app.

And something totally offtopic: I don't know if you're interested in the smallest possible binary size but here it goes. I am pretty sure MSVC2015 static builds will be very minimal in size. However, I don't know if it supports all the c++14 features you use.

**Comment by Martchus** [comment]
I know about QFileSystemWatcher. It would be interesting as an optional feature which could be enabled on directory level. Since syncthing-inotify is already available, the feature is not on the very top of my TODO list (next thing is pausing/resuming directories).

I always cross-compile the Windows version under Arch Linux and will not change that. I think the size is small enough. If I wanted to make it smaller I would start by building Qt with minimal dependencies (eg. don't include harfbuzz).

> Although the GUI would need some work IMO.

I'm open for ideas how to improve. I have already noted some graphical glitches in the Windows version but currently don't care enough to fix them.

**Comment by sledgehammer999** [comment]
>I'm open for ideas how to improve. I have already noted some graphical glitches in the Windows version but currently don't care enough to fix them.

Me neither. The app will mostly stay in the tray anyway. For me its job, is a quick way to see the status of syncthing, folders and devices. And for that it is very good atm.

If I discover something annoying, I'll submit a PR. I know c++ and Qt so that shouldn't be a problem.

Thanks for the app.

**Comment by Martchus** [comment]
Fixed the path. It is now `/home/$USER/.config/syncthingtray.ini` under Linux. Not sure what Qt does under Windows now. The application name is now actually used as organization.

**Comment by sledgehammer999** [comment]
Are you sure it is wise to dump it inside .config? Shouldn't it have its own subdir?
PS: (Without actually running it) On Windows 7 I think it will be `C:\Users\<username>\AppData\Roaming\syncthingtray.ini`

**Comment by Martchus** [comment]
Looks fine for me since only a single config file is required. Under Linux it is actually quite common to put a single file under .config. At least mine is full of those files for various applications, eg. pavucontrol.ini.
