### ISSUE TITLE
Autostart not working (Windows 11 - Winget-Install)

### ISSUE THREAD

**Issue by Nordlicht-13** [Martchus/syncthingtray#302]
**Steps to reproduce**
1. Install on a Windows 11 system using "winget install --id=Martchus.syncthingtray  -e"
Installed files are under C:\Users\username\AppData\Local\Microsoft\WinGet\Packages\Martchus.syncthingtray_Microsoft.Winget.Source_8wekyb3d8bbwe\syncthingtray-1.6.4-x86_64-w64-mingw32.exe

2. Select the autostart in the settings.
In the registry I can see the syncthingtray entry under "Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run"

3. Restart Windows and the syncthingtray won't start up

**Expected behavior**
Running syncthingtray with the trayicon in the tray.

**Comment by Martchus** [comment]
Please report issues with community provided downloads on the respective issue tracker (and link it here). If the issue is not winget-specific you can reopen the issue here but please provide steps to reproduce that don't involve wget then.

You said "In the registry I can see the syncthingtray entry …". Where does the entry point to? It is supposed to point to the Syncthing Tray executable which must therefore remain at the same location - otherwise the autostart entry would become invalid.
