### ISSUE TITLE
[KDE Neon] Doesn't show up in the Plasma Add-On Installer

### ISSUE THREAD

**Issue by geokon-gh** [Martchus/syncthingtray#32]
This widget doesn't show up in the Plasma Add-On Installer under KDE Neon nor in Kubuntu 18.10 even though it shows up on the website: https://store.kde.org/p/1193680/

I'm not really sure why or how to debug this further. Or is this widget only installable by building and installing myself with CMake?

**Comment by Martchus** [comment]
I know that it doesn't show up. Creating the store page alone doesn't help much since I have not even uploaded files there.

Not sure whether it is possible to create a distribution-neutral binary package for the plasmoid because it relies on a plugin written in C++ which relies on multiple other libraries written in C++.

I honestly wouldn't put that much effort into it considering that a viable solution is unlikely.

Maybe creating a native package for KDE Neon (and possibly other Debian-based distributions) is a better idea.

**Comment by Martchus** [comment]
I don't think this is possible because the Plasmoid needs C++ libraries.
