### ISSUE TITLE
Up to date OpenSuSE packages

### ISSUE THREAD

**Issue by terba** [Martchus/syncthingtray#6]
First of all thank you for making this!

Please take care of the OpenSuSE builds, they are failed. I would like to upgrade to a newer version, but had difficulties compiling the sources myself.

Thanks!

**Comment by Martchus** [comment]
I tried to improve the rpm last time I tried to update them because I wasn't following the standards but I just got more errors.

Since I didn't get any feedback for the rpm packages I stopped working on them because I currently don't need the latest version myself under SUSE. Maybe I'll continue but if you want this decently packaged for SUSE I guess you better ask the developers there. Maybe they can pick up the packages from my home repo. I would help maintaining the packages of course.

**Comment by Martchus** [comment]
At least `c++utilities` seems to build now. However, I'm not sure about this error (which is fortunately not considered bad enough to let the whole build fail):

```
[   79s] libc++utilities4.x86_64: E: devel-file-in-non-devel-package (Badness: 50) /usr/lib64/libc++utilities.so
[   79s] A development file (usually source code) is located in a non-devel package. If
[   79s] you want to include source code in your package, be sure to create a
[   79s] development package.
```

The library is *not* a devel file so it actually makes sense to put it in a non-devel-package.

Note that the build under Leap fails because gcc-c++-4.8 is just too old. I can not support legacy compiler.

**Comment by terba** [comment]
Thanks for looking into this. Then I will not try to compile again, as I have no machine with gcc above 4.8. So I will continue to use the 0.4.1 version of syncthingtray :(

**Comment by Martchus** [comment]
I guess I know why some of my packages are still failing and will fix it (eg. Syncthing Tray currently requires at least Qt 5.8 but Tumbleweed only provides 5.7.1).

If you use an old version of GCC you also have to stick with older versions of software. That also explains why you had difficulties compiling it yourself. If you don't like to use old software, try Tumbleweed. In my opinion it is worth it and it is very stable/well tested.

**Comment by terba** [comment]
Thanks for the reply!

**Comment by Martchus** [comment]
I'm closing this because everything builds now for Tumbleweed.

I also added Leap 42.3 as repo but it fails like 42.2 because `nothing provides gcc-c++ >= 5`. So it seems that not even the next Leap version will provide recent enough GCC.

Maybe I can provide a statically linked binary so everything is distributed as one self-containing executable. I already use this approach to provide Windows. This would have the same disadvantages of course (eg. no Dolphin integration, no Qt WebKit).
