### ISSUE TITLE
systemd integration: Support system-wide units in addition to user unit

### ISSUE THREAD

**Issue by nathanielcwm** [Martchus/syncthingtray#61]
I enable syncthing using systemd like so: syncthing@nathanielcwm
However when I list that as the unit is syncthing@nathanielcwm it doesn't seem to work.

I believe it could be because it seems to be hardcoded to check for user units.

**Comment by Martchus** [comment]
It is not "hardcoded" to check for user units. The problem is that it only speaks to systemd using the *session*-wide D-Bus service (and not the system-wide D-Bus service). Via this service only user units are controlled.

I could add a checkbox to make it use the system-wide D-Bus service. However, I'm not sure whether starting and stopping would be possible. Likely this is not permitted by default - but if the status is sufficient for you or you somehow have the permission that could make sense.

**Comment by nathanielcwm** [comment]
sorry for being misinformed. i don't mind at all if it can't be started or stopped i'm mostly just interested in the status.

**Comment by Martchus** [comment]
I'll assign myself when I start to work on this. I actually have a setup like this as well and therefore the same use case. I've just haven't had the time time to implement it yet. If you want to try implementing it yourself let me know (shouldn't be difficult to implement).

**Comment by Martchus** [comment]
I implemented the feature. Even starting and stopping works if systemd can ask for authorization:

![Screenshot_20191218_002559](https://user-images.githubusercontent.com/10248953/71042799-0935ff00-212d-11ea-93c6-659a7978f872.png)
