### ISSUE TITLE
Helping you with a proper way to build for macOS, be that on a local machine or CI

### ISSUE THREAD

**Issue by ytain** [Martchus/syncthingtray#64]
I've tried the macports version and didn't work because macports never worked for me in the past 5 years.

Here is what I did to compile syncthingtray successfully on macOS Catalina 10.15.3.

First you have to install the Qt5 dependency with homebrew by using `brew install Qt5`.

I made my own shell script to automate compiling the cmake projects so I'm sharing it with you:

```
#!/usr/bin/bash

repo[0]='c++utilities'
repocommand[0]='-DBUILD_SHARED_LIBS=OFF -DCMAKE_CXX_FLAGS=-std=c++17 -DSTATIC_LINKAGE:BOOL=ON -DUSE_STANDARD_FILESYSTEM=OFF'
repo[1]='qtutilities'
repocommand[1]='-DBUILD_SHARED_LIBS=OFF -DCMAKE_CXX_FLAGS=-std=c++17 -DSTATIC_LINKAGE:BOOL=ON'
repo[2]='syncthingtray'
repocommand[2]='-DBUILD_SHARED_LIBS=OFF -DCMAKE_CXX_FLAGS=-std=c++17 -DSTATIC_LINKAGE:BOOL=ON -DQT_LINKAGE=STATIC'

current_folder=$(PWD)
#uncomment the below line to show the invocation of compiler/linker commands in case of errors
#makefile_verbose='-DCMAKE_VERBOSE_MAKEFILE=ON'

function compile_with_cmake() {
    cd $1
    if [ -e CMakeLists.txt ]; then
	echo "==========================================================================="
	echo "Compiling $1 with CMake"
	echo "==========================================================================="
	echo "==========================================================================="
	echo "Uninstalling old version from final folder"
	if [ -d build ]; then
		cd build
		if [ -f install_manifest.txt ]; then
			xargs rm < install_manifest.txt
		fi
		cd ..
	fi
	echo "==========================================================================="
	if [ -d build ]; then
	    echo "Emptying the build folder ..."
	    echo "==========================================================================="
	    rm -rf build
	    mkdir build
	else 
	    mkdir build
	fi
	cd build
	local output_folder=$current_folder'/final'
	local library_path=$output_folder'/lib'
	local pkgconfigpath=$library_path'/pkgconfig'
	local args_to_be_passed_to_cmake="$2"
	export LT_SYS_LIBRARY_PATH="$library_path"
	export LDFLAGS="$library_path"
	export PKG_CONFIG_PATH="${pkgconfigpath}"
	LDFLAGS="-L${output_folder}/lib"  cmake .. $makefile_verbose -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE -DCMAKE_BUILD_WITH_INSTALL_RPATH=FALSE -DCMAKE_INSTALL_RPATH=$library_path -DCMAKE_BUILD_TYPE="Release" -DCMAKE_PREFIX_PATH=$output_folder -DCMAKE_INSTALL_PREFIX=$output_folder $args_to_be_passed_to_cmake
	cmake --build .
	cmake --build . --target install
	echo "==========================================================================="
	cd ..
    fi
    cd ..
}

function git_check() {
    [ $(git rev-parse HEAD) = $(git ls-remote $(git rev-parse --abbrev-ref @{u} | sed 's/\// /g') | cut -f1) ] && return 0 || return 1
}

function update_and_compile() {
    cd $1
    echo "Checking $1"
    git_check
    local res=$?
    if [ $res -eq 1 ]; then
	git pull
	cd ..
	compile_with_cmake "$1" "$2"
	cd $1
    fi
    cd ..
}

package="$1"
empty=""
if [ "$package" = "$empty" ]
then
    package="all"
fi

length=${#repo[*]}

if [ "$package" = "all" ]
then
    for (( i=0; i<=$(( $length -1 )); i++ ))
    do
	update_and_compile ${repo[$i]} "${repocommand[$i]}"
    done
else
    if [ "$package" = "list" ]
    then
	for (( i=0; i<=$(( $length -1 )); i++ ))
	do
	    echo "${repo[$i]}"
	done
    else
	for (( i=0; i<=$(( $length -1 )); i++ ))
	do
	    if [ "$package" = "${repo[$i]}" ]
	    then 
		compile_with_cmake ${repo[$i]} "${repocommand[$i]}"
	    fi
	done
    fi
fi
```

Be aware that the script will work only on macOS because of `sed` utility differing from the linux one.

Create a folder and in that folder clone the repositories required for syncthingtray like `c++utilities`, `qtutilities` and `syncthingtray`.

Put the above shell script in that folder with your prefered name and make it executable with `chmod +x <name of the script>`.

You can invoke the shell script in the following way: 

```
cd <name of the folder containing the repos>
./<name of the shell script> c++utilities
./<name of the shell script> qtutilities
./<name of the shell script> syncthingtray
```

You can also use that shell script to build a newer version if run it without arguments to check the repos for updates and fetch the updated files then compile the new version.

And you'll find the executables in the folder `<name of the folder containing the repos>/final/bin`

The built `syncthingtray.app` runs properly with no crash.

I had to apply some modifications to make it work cause in 
```
(rev c834f8923d70456adf5110e7b3228850834ada8c)
c++utilities/cmake/modules/3rdParty.cmake
```
at line 414 I had to remove the parameter `-static-libgcc` since it is not supported by xcode clang (Xcode 11.3.1)
and in `syncthingtray/connector/syncthingdev.h` and `syncthingtray/connector/syncthingdir.h` `(rev 8971f294e80addc859b823890b4a09fcfd3fb220)` I had to add one line `#include <unordered_map>` cause it errored on the absence of unordered_map template.

You could make it all of it in a cask for homebrew.

**Comment by Martchus** [comment]
Thanks for sharing.

> You could make it all of it in a cask for homebrew.

Contributions in that regard are welcome. I use neither Mac nor Homebrew so I won't implement it myself, though.

---

A few notes regarding certain CMake options:

* `-DBUILD_SHARED_LIBS=OFF`: That should be the default.
* `-DCMAKE_CXX_FLAGS=-std=c++17`: My project files should take care of setting the C++ version appropriately. Did you run into problems without that option? (You shouldn't have.)
* `-DSTATIC_LINKAGE:BOOL=ON -DQT_LINKAGE=STATIC`: Interesting that you're preferring static linkage and even use a static build of Qt. I'm glad to see that this configuration actually works (beside the few amendments you needed to make) because so far I'm only testing this configuration for the Windows build. Apparently it makes no difference in practice but strictly you need to use `-DQT_LINKATE` when building `qtutilities` as well.
* `-DCMAKE_VERBOSE_MAKEFILE=ON`: You can also use `make VERBOSE=1`.

---

So it seems the following points need to be improved:

1. There should be an option to omit `-static-libgcc` despite aiming for an otherwise statically linked build (e.g. `NO_STATIC_LIBGCC`). For the sake of consistency it would make sense to have a similar option for `-static-libstdc++` (e.g. `NO_STATIC_CXX_STD_LIB`). By the way, the `-static` option is already omitted in any case when building for Apple platforms because it seems to be never supported; but I suppose that's not the case for `-static-libgcc` and `-static-libstdc++`. At least I remember to build it successfully with these options (using Clang and libstdc++).
2. Fix the missing include in the headers you've mentioned. That it works on other platforms is just luck.

If you like, you can create a PR for these improvements (at least for 2. you likely have the patch anyways). Otherwise I can take care of it as well.

**Comment by Martchus** [comment]
I'm going to improve points 1. and 2. myself now.

Not sure whether it makes sense to keep the issue open when it is implemented. From my point of view it doesn't make sense to have an open ticket for every conceivable packaging/distribution option.

The instructions contained by this ticket seem useful. They could be added in form of a condensed script and added to the scripts directory within this repository. The script could be mentioned by the build instructions in the README. Or one creates a homebrew recipe from it. That would likely be even more useful.

**Comment by ytain** [comment]
Sorry for not replying to your initial reply, I was fighting with the Qt5 building system to produce static libraries and I failed. That's because the homebrew version of Qt5 is of shared version.

With regard to your observations about cmake arguments that I used in the shell script, I have to clarify: the `BUILD_SHARED_OFF` is a carry over from another shell script I used for creating static libraries for another project of mine. The shell script here is just a generic one that I use in every project of mine. Only the array of values are different for every project.

As for the `-DCMAKE_CXX_FLAGS=-std=c++17`, that's because when I saw the compiler invocation, it shows the `-std=gnu++17` and the Apple clang compiler would spew warnings (lots). With that flag, the warnings don't show. I don't know where the `gnu++17` comes from, cause in my other projects I use, I never saw it (same for `-static-libgcc`). I guess you tailored the cmake modules based on the use of `osxcross` process that you used to cross compile to macOS version, but beware of that process cause the environment variables will differ for osxcross and the original system. And there's some differences between Apple clang and as well the standard distribution of LLVM.

Not a problem if you close the ticket. I just wanted to share, that's all.

**Comment by Martchus** [comment]
> I was fighting with the Qt5 building system to produce static libraries and I failed. That's because the homebrew version of Qt5 is of shared version.

Ok, but if you're not using a static build of Qt in the end you should get rid of `-DQT_LINKAGE=STATIC`. This flag is used to indicate that the provided version of Qt is a static build. It causes the build system to link against certain plugins statically and to take care of special requirements of Qt resource system in that case. Seems like it doesn't interfere when using a shared build of Qt but I'd not recommend that. Likely it makes even sense to get rid of `-DSTATIC_LINKAGE:BOOL=ON` as well. This would also avoid that my build script would add `-static-libgcc`.

I'm setting the C++ standard within CMake via the target property `CXX_STANDARD`. That CMake generates a compiler flag from that which does not work with your compiler might be a  CMake bug as CMake is actually supposed to abstract this detail. Unfortunately I don't know enough about your setup so I can not really help with that. But the flag with `gnu` in it is definitely not hard-coded in my build scripts.

The `-static-libgcc` on the other hand really comes from my build script. It is enabled when one enables static linkage because that makes sense on my primary target platforms (GNU/Linux, mingw-w64) but I'll make that configurable.

**Comment by ytain** [comment]
OK, those two flags about static use of Qt libraries didn't seem to affect the compilation process.

I never had to use `CXX_STANDARD` because I used `target_compile_features` ( https://crascit.com/2015/03/28/enabling-cxx11-in-cmake/ ) to enable properly the right level of CXX_STANDARD.

**Comment by Martchus** [comment]
Your script is acknowledged and I've fixed the missing includes and added opt-outs for problematic linker flags.

**Comment by metbril** [comment]
Sorry to bump this. I've been searching https://brew.sh/ etc. for a working build of syncthingtray. I couldn't find it. Are there any plans on adding it there?

**Comment by Martchus** [comment]
There are no plans on my side to distribute binaries/packages for Mac. There's a MacPorts version but it is out of maintenance (see https://ports.macports.org/port/syncthingtray/details).
