### ISSUE TITLE
Add Fedora 33 builds to OBS

### ISSUE THREAD

**Issue by Skirmisher** [Martchus/syncthingtray#80]
Fedora 33 has been GA for about two weeks now. Thanks in advance!

**Comment by Martchus** [comment]
I've been adding the repo. Let's  see whether every package builds. It might take a while until everything is published.

**Comment by Martchus** [comment]
Unfortunately the packages fail to build. Seems like some rpm macros behave differently under Fedora 33.

**Comment by Skirmisher** [comment]
Hmm hmm. I grabbed the srpm for c++utilities to take a look. Seems to be pretty simple, just a few changes necessary:

- `%{?fedora_version}` should be `%{?fedora}`
- As of F33, Fedora has `%cmake_build`, `%cmake_install`, and `%ctest` macros like openSUSE, which account for `%cmake` creating an out-of-source build directory. These have been backported to 32 and 31 as well. You can change your Fedora version checks to <F31, or just drop the checks altogether if you don't care about supporting EOL releases. See the change doc [here](https://fedoraproject.org/wiki/Changes/CMake_to_do_out-of-source_builds).
  - As a side note, openSUSE appears to have [deprecated `%make_jobs` in favor of `%cmake_build`](https://en.opensuse.org/openSUSE:Packaging_Conventions_RPM_Macros#.25make_jobs).

A quick skim of syncthingtray's spec tells me it should work after these changes as well.

Let me know if you want me to test anything else!

**Comment by Martchus** [comment]
I don't know why this test and others fail under recent Fedora versions:

```
[  157s] test 1
[  157s]     Start 1: c++utilities_run_tests
[  157s] 
[  157s] 1: Test command: /home/abuild/rpmbuild/BUILD/cpp-utilities-5.8.0/x86_64-redhat-linux-gnu/c++utilities_tests
[  157s] 1: Test timeout computed to be: 10000000
[  157s] 1: /home/abuild/rpmbuild/BUILD/cpp-utilities-5.8.0/testfiles/
[  157s] 1: ./testfiles/
[  157s] 1: Directory used to store working copies:
[  157s] 1: ./testfiles/workingdir/
[  157s] 1: [1mExecuting test cases ...[0m
[  157s] 1: ...............
[  157s] 1/1 Test #1: c++utilities_run_tests ...........Child aborted***Exception:   0.01 sec
[  157s] 
[  157s] 0% tests passed, 1 tests failed out of 1
[  157s] 
[  157s] Total Test time (real) =   0.01 sec
[  157s] 
[  157s] The following tests FAILED:
[  157s] 	  1 - c++utilities_run_tests (Child aborted)
```

Under Leap I'm getting `Exception: SegFault` in tests. Maybe that's related. And apparently my attempts to comment-out the running the tests are not working.

Note that the new macros were not present in Fedora < 33 - at least within my OBS build setup. So I'm only using the new macros for Fedora >= 33. I'm also generally moving to Ninja but it is unresolvable in Fedora so that's openSUSE-only for now. 

I'm currently tired of this damn RPM packaging but at least the repo is now initially populated: https://download.opensuse.org/repositories/home:/mkittler/Fedora_33/x86_64

**Comment by Martchus** [comment]
It should work now, everything got rebuild on 01.12.
