### ISSUE TITLE
Web view support missing on Windows

### ISSUE THREAD

**Issue by x3rAx** [Martchus/syncthingtray#85]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: 1.1.1, ???, ???
* Qt version: 5.12.2 / 6.0.0
* C++ compiler (name and version): ???
* C++ standard library (name and version): ???
* Operating system (name and version): Windows 10 Pro 2004

**Bug description**
On Windows the "Web view" settings section displays the message "Syncthing Tray has not been built with web view support utilizing either Qt WebKit or QtWebEngine. The Web UI will be opened in the default web browser instead."

As this message states, the web browser opens when I click "Open Syncthing".

**Steps to reproduce**
1. Go to settings
2. Select "Web view"

**Expected behavior**
There should be the same settings page for the web view as it is on Linux and the web UI should open in a separate web view window, not the default browser.

**Screenshots**
N/A

**Additional context**
I consider this as a bug because it sounds as if the Windows build script is missing an option.

Thank you, I really like this tool. I use it on my Linux laptop and I'd love to replace SyncTrayzor with SyncthinTray on my Windows PC aswell.

**Comment by Martchus** [comment]
I am not going to deploy a web browser for Windows and there's no Qt module to easily use Windows' native web view. Shipping a web browser is just too much effort and greatly increases the size of the installation. Under Linux it is easy as one can simply depend on the distribution-provided package for Qt WebEngine so that's a different story.

You may build it yourself with support for the built-in web view. Note that there is almost no benefit from using the built-in web view in comparison to just use the web browser you have installed anyways.

Other uses have previously noted that they like that I don't ship a web browser (unlike QSyncthingTray) because it is less bloated. I tend to agree. (Even under Arch Linux a user has already created an AUR package without Qt WebEngine dependency.)
