### ISSUE TITLE
error: ‘qmlRegisterUncreatableMetaObject’ was not declared

### ISSUE THREAD

**Issue by redjamesg** [Martchus/syncthingtray#9]
When building on Debian stretch the make results in the error:
`$SOURCE/syncthingtray/plasmoid/lib/syncthingapplet.cpp:59:134: error: ‘qmlRegisterUncreatableMetaObject’ was not declared in this scope
     qmlRegisterUncreatableMetaObject(Data::staticMetaObject, "martchus.syncthingplasmoid", 0, 6, "Data", QStringLiteral("only enums"));`
This is with the latest git checkout of cpp-utilities, qtutilities, syncthingtray and subdirs.

The question is if the qmlRegisterUncreatableMetaObject has been moved to another support package or if the code itself has been altered where the reference to this function is taking place before it is actually available.
How ever compile of version 0.6.3 on the same system was carried out without any iussues of this type.

**Comment by Martchus** [comment]
According to https://packages.debian.org/stretch/qtdeclarative5-dev Debian stretch only provides Qt 5.7.1 which doesn't provide `https://packages.debian.org/stretch/qtdeclarative5-dev`. [As documented], building the plasmoid requires Qt 5.8.0 or newer.

To resolve this issue you can:
* Update to newer Qt version (eg. by using the binaries provided by the Qt project or building Qt yourself)
* Use the Qt Widgets-based variant instead of the plasmoid. To disable building the plasmoid, add `-DNO_PLASMOID:BOOL=ON` to CMake arguments. If the build then still fails, that would be a bug.

**Comment by redjamesg** [comment]
Good to know, I wasn't quite expecting this, but the `-DNO_PLASMOID:BOOL=ON` made an environment that made it possible to build.
Yet execution of syncthingtray resulted in a `syncthingtray: symbol lookup error: syncthingtray: undefined symbol: _ZN20ApplicationUtilities15NoColorArgumentC1Ev` error.

**Comment by Martchus** [comment]
Seems like it is loading an old version of the `c++utilities` library at runtime. Ensure `c++utilities` 4.10 or newer is loaded.

---

Of course the version of other dependencies is important as well: So also ensure the correct version of `qtutilities` (at least 5.8) is loaded. The different backend libraries build within `syncthingtray` must always match exactly the version of `syncthingtray` itself.

**Comment by Martchus** [comment]
BTW:

**Comment by redjamesg** [comment]
I was using the build instruction, and since it was a completely fresh git clone of everything needed I would expect the c++utilities to be the required version as well.

Like earlier stated I had an older checkout of every git repository matching the release of syncthingtray v. 6.3.0 that had no trouble building, so to make sure there wasn't anything messing up in regards to a new release, I decided to scrap my earlier build environment and follow the buildsteps with a clean environment.

During with I noticed a few dev packages needed to be added, and just to extra careful I made a complete upgrade of everything on my debian install so it is a fully up to date debian stretch.

**Comment by Martchus** [comment]
> I was using the build instruction, and since it was a completely fresh git clone of everything needed I would expect the c++utilities to be the required version as well.

Since it could be built, there is no doubt that your source are up-to-date.

> I decided to scrap my earlier build environment and follow the buildsteps with a clean environment.

Again, your build environment is not the problem.

---

The problem is the *runtime* environment. That should actually be obvious, since you say the error happens at runtime. It is likely that Linux tries to load an older version of `c++utilities.so.4` which is flying around in your runtime environment.

Finding out which libraries are used at runtime by an application under Linux is very simple. Here an example for `syncthingtray`:
```
LD_DEBUG=libs syncthingtray
LD_DEBUG=help syncthingtray # show other useful debug options
```

Conrolling the dynamic linker/loader to adjust its behaviour is well described. Just read `man ld.so`.

---
> debian install so it is a fully up to date debian stretch

BTW: Distribution specific information is likely useless to me because the probability I'm using that exact distribution as well is quite small. It makes more sense describe the relevant parts of your software stack more explicitly, eg. "I'm using Qt *5.7.1* as provided by Debian Stretch.".

**Comment by redjamesg** [comment]
You were right, the /lib installed wasn't correctly linked to the running environment.
