### ISSUE TITLE
Add Fedora 34 builds to OBS

### ISSUE THREAD

**Issue by Skirmisher** [Martchus/syncthingtray#92]
It's that time again ^^ Thanks in advance!

**Comment by Martchus** [comment]
I've been adding the repository and all package have been built yet. Now OBS only needs to publish but there's nothing I can do to speed that up. Note that the aarch64 builds are currently broken. That's likely because the [related project](https://build.opensuse.org/repositories/Fedora:34) still refers to the Fedora 33 repository. Fixing this is also out of scope here. (It looks like the path has been fixed after I've mentioned the problem but it'll likely take some time to apply.)

**Comment by Skirmisher** [comment]
I see, thanks again!
